### ISSUE TITLE
Configure Okta authentication via OIDC

### ISSUE THREAD

**Issue by spinside** [tchiotludo/akhq#1023]
I tried to configure Okta with the following settings:
```
micronaut:
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          okta:
            client-id: "client-id"
            client-secret: "client-secret"
            openid:
              issuer: "https://my.okta.com"
              configuration-path: "/.well-known/oauth-authorization-server" 
      token:
        jwt:
          signatures:
            secret:
              generator:
                secret: <Redacted>
akhq:
    security:
      default-group: no-roles
      endpoints:
        login:
          enabled: true
        logout:
          enabled: true  

      oidc:
        enabled: true
        providers:
          okta:
            #use-oidc-claim: true
            label: "Login with Okta"
            username-field: preferred_username
            default-group: admin
```
When I click on login it redirects me to Okta. I can enter my credentials and get redirected back to the app. So far so good.

After this step AKHQ tries to check the JWT validity. There it's not going as expected:
```
2022-02-16 18:16:22,837 WARN  r-thread-2 org.akhq.log.access        [Date: 2022-02-16T18:16:22.835266Z] [Duration: 1 ms] [Url: GET /api/auths] [Status: 500] [Ip: /10.48.224.20] [User: Anonymous]
2022-02-16 18:16:22,933 TRACE pGroup-1-4 thorizationResponseHandler Token endpoint returned a success response. Validating the JWT
2022-02-16 18:16:22,933 TRACE pGroup-1-4 enIdTokenResponseValidator Validating the JWT signature using the JWKS uri [null]
2022-02-16 18:16:22,934 ERROR r-thread-4 o.a.c.ErrorController      null
java.lang.NullPointerException: null
        at java.base/java.util.concurrent.ConcurrentHashMap.get(Unknown Source)
        at java.base/java.util.concurrent.ConcurrentHashMap.containsKey(Unknown Source)
        at io.micronaut.security.oauth2.endpoint.token.response.validation.DefaultOpenIdTokenResponseValidator.jwksSignatureForOpenIdProviderMetadata(DefaultOpenIdTokenResponseValidator.java:172)
        at io.micronaut.security.oauth2.endpoint.token.response.validation.DefaultOpenIdTokenResponseValidator.parseJwtWithValidSignature(DefaultOpenIdTokenResponseValidator.java:160)
        at io.micronaut.security.oauth2.endpoint.token.response.validation.DefaultOpenIdTokenResponseValidator.validate(DefaultOpenIdTokenResponseValidator.java:84)
        at io.micronaut.security.oauth2.endpoint.authorization.response.DefaultOpenIdAuthorizationResponseHandler.validateOpenIdTokenResponse(DefaultOpenIdAuthorizationResponseHandler.java:200)
        at io.micronaut.security.oauth2.endpoint.authorization.response.DefaultOpenIdAuthorizationResponseHandler.lambda$createAuthenticationResponse$1(DefaultOpenIdAuthorizationResponseHandler.java:158)
        at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:94)
        at reactor.core.publisher.Flux.subscribe(Flux.java:8402)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.onNext(FluxSwitchMap.java:236)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.drain(FluxSwitchMap.java:355)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapMain.innerNext(FluxSwitchMap.java:413)
        at reactor.core.publisher.FluxSwitchMap$SwitchMapInner.onNext(FluxSwitchMap.java:512)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
        at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
        at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onNext(WebMetricsPublisher.java:180)
        at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onNext(WebMetricsPublisher.java:157)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.lambda$onNext$1(ClientServerRequestTracingPublisher.java:60)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
        at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.onNext(ClientServerRequestTracingPublisher.java:60)
        at io.micronaut.http.client.filters.ClientServerRequestTracingPublisher$1.onNext(ClientServerRequestTracingPublisher.java:52)
        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
        at reactor.core.publisher.FluxCreate$NoOverflowBaseAsyncSink.next(FluxCreate.java:648)
        at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154)
        at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2405)
        at io.micronaut.http.client.netty.DefaultHttpClient$11.channelReadInstrumented(DefaultHttpClient.java:2322)
        at io.micronaut.http.client.netty.DefaultHttpClient$SimpleChannelInboundHandlerInstrumented.channelRead0(DefaultHttpClient.java:3072)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:214)
        at io.micronaut.http.netty.stream.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:189)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
```
(Enabled debug logging)
I can't figure out what I'm doing wrong. Any help/input would be appreciated.

**Comment by tchiotludo** [comment]
The stacktrace lead me to this : 
```java 
    protected JwksSignature jwksSignatureForOpenIdProviderMetadata(@NonNull OpenIdProviderMetadata openIdProviderMetadata) {
        final String jwksuri = openIdProviderMetadata.getJwksUri();
        if (!jwksSignatures.containsKey(jwksuri)) {
            JwksSignatureConfigurationProperties config = new JwksSignatureConfigurationProperties();
            config.setUrl(openIdProviderMetadata.getJwksUri());
            jwksSignatures.put(jwksuri, new JwksSignature(config, jwkValidator));
        }
        return jwksSignatures.get(jwksuri);
    }
```

that seems to tell the jwt token is missing `URL of the Open ID Provider's JSON Web Key Set`

As I understand the well know is missing an url in order to be compatible

**Comment by spinside** [comment]
Hmm i'm having trouble understanding what this exactly means. I tried adding the following:
```
      token:
        jwt:
          enabled: true
          cookie:
            enabled: true
          signatures:
            secret:
              generator:
                secret: secret
            jwks:
              okta:
                url: "https://my.okta.com/oauth2/default"
```
Based on the following documentation: https://developer.okta.com/code/dotnet/jwt-validation/#get-the-signing-keys and 
The issuer appears to be the same as the jwks validation url.

I used this to get the right settings for the jwks url:
https://micronaut-projects.github.io/micronaut-security/latest/guide/#jwks

As far as I understand in the following diagram:
https://micronaut-projects.github.io/micronaut-security/latest/guide/#bearerToken
The whole authentication is going well until the JWT needs to be validated.


However I still got the `java.lang.NullPointerException: null`

Am I setting this correctly? Because here: https://akhq.io/docs/configuration/authentifications/oidc.html I see no mention at all about setting the jwks url.

**Comment by tchiotludo** [comment]
To be honest, I'am completely blindness so I only try to give you some insight. I know people have a working installation, but I never used myself Okta. 

All let me think the url must be provided inside the jwt token in response of auth that lead to this null pointer, but clearly I don't known how to configure that. 

Since AKHQ rely only on micronaut, I really think there is a special configuration issue on your side hard to debug without more details. 

Maybe you can paste the well-known ? as I understand, the must be a property `jwksUri` on this url

**Comment by spinside** [comment]
Okay, I figured it out, it had to do with me mixing up OIDC and OAUTH

Correct config for Okta oidc:
```
    security:
      enabled: true
      oauth2:
        enabled: true
        clients:
          okta:
            scopes:
              - openid
              - email
              - profile
              - groups
            client-id: "client-id"
            client-secret: "client-secret"
            openid:
              issuer: https://mydomain.okta.com
              configuration-path: "/.well-known/openid-configuration" 
```
