### ISSUE TITLE
Topics not loading for OCI Streaming - Internal Server Error: Error for List Log dir

### ISSUE THREAD

**Issue by linkedby-data** [tchiotludo/akhq#1034]
**Describe the bug**
Hi,
I'm trying to use akhd v0.20.0 connected with OCI Streaming, but the topics don't load, it shows the message Internal Server Error: Error for List Log dir.

**Set up**
Run latest image in docker:
```
akhq:
  connections:
    linkedby-cluster-sasl:
      properties:
        bootstrap.servers: 'server:9092'
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="username" password="password";'
```
**Steps to Reproduce**

1. docker run -d -p 8080:8080 -v /path/to/application.yml:/app/application.yml tchiotludo/akhq
2. http://localhost:8080

**Screenshots**
![Screenshot from 2022-03-04 22-48-48](https://user-images.githubusercontent.com/92417970/156862839-6e785652-291f-4a55-aff4-45a6af049e90.png)

**Additional context**
Log with erros:
```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.2.2)

2022-03-05 01:51:37,930 INFO  main       i.m.runtime.Micronaut      Startup completed in 1390ms. Server Running: http://6bd38b2dfecb:8080
2022-03-05 01:52:21,317 INFO  r-thread-1 org.akhq.log.access        [Date: 2022-03-05T01:52:20.7456Z] [Duration: 572 ms] [Url: GET /] [Status: 307] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,436 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2022-03-05T01:52:21.427696Z] [Duration: 1 ms] [Url: GET /ui] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,548 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2022-03-05T01:52:21.547353Z] [Duration: 0 ms] [Url: GET /ui/static/css/main.ae4160af.chunk.css] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,587 INFO  pGroup-1-6 org.akhq.log.access        [Date: 2022-03-05T01:52:21.587441Z] [Duration: 0 ms] [Url: GET /ui/static/js/main.ea7834c2.chunk.js] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,610 INFO  pGroup-1-7 org.akhq.log.access        [Date: 2022-03-05T01:52:21.609606Z] [Duration: 0 ms] [Url: GET /ui/static/js/main.ea7834c2.chunk.js] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,637 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2022-03-05T01:52:21.636886Z] [Duration: 0 ms] [Url: GET /ui/static/js/2.f34dda50.chunk.js] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,685 INFO  pGroup-1-8 org.akhq.log.access        [Date: 2022-03-05T01:52:21.684956Z] [Duration: 0 ms] [Url: GET /ui/static/js/2.f34dda50.chunk.js] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,734 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2022-03-05T01:52:21.733956Z] [Duration: 0 ms] [Url: GET /ui/static/css/2.1e4ddb81.chunk.css] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,844 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2022-03-05T01:52:21.844128Z] [Duration: 0 ms] [Url: GET /ui/manifest.json] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,952 INFO  r-thread-1 org.akhq.log.access        [Date: 2022-03-05T01:52:21.797424Z] [Duration: 155 ms] [Url: GET /api/auths] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,956 INFO  r-thread-4 org.akhq.log.access        [Date: 2022-03-05T01:52:21.791006Z] [Duration: 165 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:21,992 INFO  r-thread-1 org.akhq.log.access        [Date: 2022-03-05T01:52:21.988093Z] [Duration: 4 ms] [Url: GET /api/cluster] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:22,009 INFO  r-thread-2 org.akhq.log.access        [Date: 2022-03-05T01:52:22.008293Z] [Duration: 1 ms] [Url: GET /api/cluster] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:22,067 INFO  pGroup-1-9 org.akhq.log.access        [Date: 2022-03-05T01:52:22.067051Z] [Duration: 0 ms] [Url: GET /ui/static/media/icon.648ce9c8.svg] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:22,174 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2022-03-05T01:52:22.172514Z] [Duration: 1 ms] [Url: GET /ui/static/media/fontawesome-webfont.af7ae505.woff2] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:22,221 INFO  Group-1-10 org.akhq.log.access        [Date: 2022-03-05T01:52:22.220991Z] [Duration: 0 ms] [Url: GET /ui/static/media/logo.45903e1f.svg] [Status: 200] [Ip: /172.17.0.1] [User: -]
2022-03-05 01:52:31,069 ERROR r-thread-4 o.a.c.ErrorController      Error for List Log dir
java.lang.RuntimeException: Error for List Log dir
	at org.akhq.utils.Logger.call(Logger.java:31)
	at org.akhq.modules.AbstractKafkaWrapper.describeLogDir(AbstractKafkaWrapper.java:245)
	at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Intercepted.describeLogDir(Unknown Source)
	at org.akhq.repositories.LogDirRepository.list(LogDirRepository.java:25)
	at org.akhq.repositories.LogDirRepository.findByTopic(LogDirRepository.java:37)
	at org.akhq.repositories.TopicRepository.findByName(TopicRepository.java:114)
	at org.akhq.repositories.TopicRepository.lambda$list$0(TopicRepository.java:58)
	at org.akhq.utils.PagedList.of(PagedList.java:70)
	at org.akhq.repositories.TopicRepository.list(TopicRepository.java:58)
	at org.akhq.controllers.TopicController.list(TopicController.java:91)
	at org.akhq.controllers.$TopicController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:656)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_LOG_DIRS
2022-03-05 01:52:31,080 WARN  r-thread-1 org.akhq.log.access        [Date: 2022-03-05T01:52:22.060061Z] [Duration: 9019 ms] [Url: GET /api/linkedby-cluster-sasl/topic] [Status: 500] [Ip: /172.17.0.1] [User: -]
```

**Comment by tchiotludo** [comment]
OCI is not supported by AKHQ due to missing Kafka Api compatibility. 
This seems to be possible to support but PR are welcome since I will never be able to test
