### ISSUE TITLE
Error for Consume with options {}

### ISSUE THREAD

**Issue by hervekhg** [tchiotludo/akhq#1035]
Hello,
When publishing and empty message on topic we have this error on AKHQ (0.20).
Any idea ?

```
2022-03-08 17:17:35,177 ERROR r-thread-4 o.a.c.ErrorController      Error for Consume with options {}
java.lang.RuntimeException: Error for Consume with options {}
        at org.akhq.utils.Debug.call(Debug.java:74)
        at org.akhq.repositories.RecordRepository.consume(RecordRepository.java:120)
        at org.akhq.controllers.TopicController.data(TopicController.java:204)
        at org.akhq.controllers.$TopicController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:656)
        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
        at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
        at org.akhq.repositories.AvroWireFormatConverter.convertValueToWireFormat(AvroWireFormatConverter.java:39)
        at org.akhq.repositories.RecordRepository.newRecord(RecordRepository.java:467)
        at org.akhq.repositories.RecordRepository.lambda$consumeNewest$14(RecordRepository.java:312)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Unknown Source)
        at java.base/java.util.stream.Nodes$CollectorTask$OfRef.doLeaf(Unknown Source)
        at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.Nodes.collect(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.evaluateToNode(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.SortedOps$OfRef.opEvaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.opEvaluateParallelLazy(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
        at org.akhq.repositories.RecordRepository.consumeNewest(RecordRepository.java:328)
        at org.akhq.repositories.RecordRepository.lambda$consume$4(RecordRepository.java:126)
        at org.akhq.utils.Debug.call(Debug.java:67)
        ... 22 common frames omitted
```

**Comment by Zewenaco** [comment]
Hello! I hope you're doing well; I'm related to this case. We are sending tombstone records to Kafka to delete events. Recently I searched and found this [jira link](https://cwiki.apache.org/confluence/display/KAFKA/KIP-810%3A+Allow+producing+records+with+null+values+in+Kafka+Console+Producer) of an improvement to producing Kafka tombstone record, could be helpful to reproduce the case locally.

In our case, we are using an implementation of KafkaNullConverter in java to produce tombstone records.

We are using `org.springframework.cloud:spring-cloud-stream-binder-kafka`
the code is something like this:
```
import org.springframework.cloud.stream.binder.kafka.KafkaNullConverter;
import org.springframework.messaging.converter.MessageConverter;

@Configuration
public class KafkaConfig {

    @Bean
    public MessageConverter kafkaNullConverter() {
        return new KafkaNullConverter();
    }
}
```
and
```
import org.springframework.cloud.stream.function.StreamBridge;
import org.springframework.kafka.support.KafkaNull;

public class Adapter {
   private final StreamBridge streamBridge;
   private final MessageConverter kafkaNullConverter;
   
   protected void publishDeleteEvent() {
      MessageHeaders messageHeaders = ...
      streamBridge.send(BINDING_NAME, kafkaNullConverter.toMessage(KafkaNull.INSTANCE, messageHeaders));
   }
   
   protected void sendMessage(Message<?> message) {
     streamBridge.send(BINDING_NAME, message);
   }
}
```
and our config in YAML is:
```
cloud:
    stream:
      kafka:
        binder:
          brokers: ${INFRA_BROKERS}
        bindings:
          out-0:
            producer:
              message-key-expression: headers['partitionKey']
              configuration:
                compression:
                  type: lz4
      bindings:
        out-0:
          binder: kafka
          destination: custom.event
          content-type: application/json
          producer:
            bufferSize: 900000
            batchTimeout: 1000
            partition-key-expression: headers['partitionKey']
            #partition-count: 3
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
```

And with a local environment with kafka when I execute kafka-console-consumer.sh like `kafka-console-consumer.sh --topic custom.event --from-beginning --bootstrap-server localhost:9092 --property print.key=true --property print.headers=true`

I got:

```
createdAt:1646821059152,partitionKey:38,service:custom,domain:custom,scst_partition:0,specversion:1.0.0,type:custom.deleted,contentType:application/json,entity:custom.entity,target-protocol:streamBridge,spring_json_header_types:{"createdAt":"java.lang.Long","partitionKey":"java.lang.String","service":"java.lang.String","domain":"java.lang.String","scst_partition":"java.lang.Integer","specversion":"java.lang.String","type":"java.lang.String","contentType":"java.lang.String","entity":"java.lang.String","target-protocol":"java.lang.String"} 38      null
```

I hope this information could be helpful; let me know if I can share with you another specific information.

**Comment by tchiotludo** [comment]
Humm really don't understand the way you produce inside topic :) 
`kafka-console-consumer.sh` seems to say the the produce values is not null as I understand (and there is json / avro / ..., lot of stuff). 
Can you send me a kafkacat with -J to have the raw output please ?

**Comment by Zewenaco** [comment]
You should be able to reproduce with a local kafka server, you could publish a topic like this:
```
./bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic test --property null.marker=NULL
```
And when you execute the consumer:
```
./bin/kafka-console-consumer.sh --topic test --from-beginning --bootstrap-server localhost:9092 --property print.key=true --property print.headers=true
```
yo should be able to see something like:
```
NO_HEADERS      null
```

And there you go, a tombstone record.

Now if you listen that server with akhq, when you list the records per topic you'll receive an error with the message of `Error for Consume with options {}`

I hope you find this information useful! 👍

**Comment by Zewenaco** [comment]
By the way, I used this versión of Kafka https://www.apache.org/dyn/closer.cgi?path=/kafka/3.1.0/kafka-3.1.0-src.tgz

**Comment by tchiotludo** [comment]
Can you try with last version please : https://github.com/tchiotludo/akhq/releases/tag/0.21.0 and reopen if it's still not work ?
