### ISSUE TITLE
Timeout of describeLogDirs on Confluent Cloud

### ISSUE THREAD

**Issue by aleksgj** [tchiotludo/akhq#1078]
We are using AKHQ (v0.20.0) with a dedicated cluster on Confluent Cloud. Last week we started gettting timeout errors when loading the topic list in AKHQ, with the following log message in the log:

```
2022-04-24 10:39:03,134 ERROR r-thread-4 o.a.c.ErrorController Error for List Log dir
java.lang.RuntimeException: Error for List Log dir
	at org.akhq.utils.Logger.call(Logger.java:31)
	at org.akhq.modules.AbstractKafkaWrapper.describeLogDir(AbstractKafkaWrapper.java:245)
	at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Intercepted.describeLogDir(Unknown Source)
	at org.akhq.repositories.LogDirRepository.list(LogDirRepository.java:25)
	at org.akhq.repositories.LogDirRepository.findByTopic(LogDirRepository.java:37)
	at org.akhq.repositories.TopicRepository.findByName(TopicRepository.java:114)
	at org.akhq.repositories.TopicRepository.lambda$list$0(TopicRepository.java:58)
	at org.akhq.utils.PagedList.of(PagedList.java:70)
	at org.akhq.repositories.TopicRepository.list(TopicRepository.java:58)
	at org.akhq.controllers.TopicController.list(TopicController.java:91)
	at org.akhq.controllers.$TopicController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:656)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeLogDirs, deadlineMs=1650796743059, tries=1, nextAllowedTryMs=1650796743222) timed out at 1650796743122 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.DisconnectException: Cancelled describeLogDirs request with correlation id 12 due to node 0 being disconnected
```

I have tried to increase timeout values in the Kafka configuration, but that only seems to delay the issue.

After searching I found issue #111 where error handling was implemented for "regular" Confluent Cloud clusters, where the Kafka client throws an error when trying to invoke describeLogDirs, and an empty list is returned. Since we also have a test cluster ("basic" tier), I was able to verify that this still works as intended. As discussed in #111, denying access to this functionality is likely a intentional desicsion by Confluent Cloud. I am uncertain how this has behaved previously with our dedicated cluster, whether describeLogDirs returned any data or not.

I have implemented a temporary workaround by building a version of AKHQ where I have permanently disabled the describeLogDirs invocation by replacing the describeLogDir method in the AbstractKafkaWrapper class with this to always return an empty HashMap:

```java
public Map<Integer, Map<String, LogDirDescription>> describeLogDir(String clusterId) throws ExecutionException, InterruptedException {
    if (!this.logDirs.containsKey(clusterId)) {
        this.logDirs.put(clusterId, Logger.call(
            () -> {
                return new HashMap<>();
            },
            "List Log dir",
            null
        ));
    }

    return this.logDirs.get(clusterId);
}
```

Would it be possible to fix this problem in the AKHQ codebase? It would be possible to catch the TimeoutException, but that would lead to very slow loading times. Make it configurable maybe?

**Comment by tchiotludo** [comment]
The better will be to add a configuration for that at the cluster level like `skip-last-record` or `skip-consumer-groups` that prevent the log dir call like the `AuthorizationException`. 

PR are welcome
