### ISSUE TITLE
Unable to view schema/topics if one Schema Registry subject does not have subject-level compatibility set (0.21.0)

### ISSUE THREAD

**Issue by amccague** [tchiotludo/akhq#1139]
This appears to be related to https://github.com/tchiotludo/akhq/issues/785

Using 0.21.0 against confluent cloud, and potentially this is specific to using schema contexts I get this error when looking to view schemas or produce to a topic:

```
io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject ':.testcontext:' does not have subject-level compatibility configured; error code: 40408
java.lang.RuntimeException: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject ':.testcontext:' does not have subject-level compatibility configured; error code: 40408
	at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLatestVersion$1(SchemaRegistryRepository.java:55)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.akhq.repositories.SchemaRegistryRepository.toSchemasLatestVersion(SchemaRegistryRepository.java:58)
	at org.akhq.repositories.SchemaRegistryRepository.listAll(SchemaRegistryRepository.java:46)
	at org.akhq.controllers.SchemaController.listSchemaForTopic(SchemaController.java:61)
	at org.akhq.controllers.$SchemaController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:656)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject ':.testcontext:' does not have subject-level compatibility configured; error code: 40408
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:297)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:367)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getConfig(RestService.java:671)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getConfig(RestService.java:652)
	at org.akhq.repositories.SchemaRegistryRepository.getDefaultConfig(SchemaRegistryRepository.java:215)
	at org.akhq.repositories.SchemaRegistryRepository.getConfig(SchemaRegistryRepository.java:230)
	at org.akhq.repositories.SchemaRegistryRepository.getLatestVersion(SchemaRegistryRepository.java:131)
	at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLatestVersion$1(SchemaRegistryRepository.java:53)
	... 30 common frames omitted
```

When setting the compatibility explicitly on the subject it works as expected.

**Comment by tchiotludo** [comment]
please update to latest version and reopen if still relevant
