### ISSUE TITLE
Null Error after login to AKHQ 0.21.0

### ISSUE THREAD

**Issue by wilkejo** [tchiotludo/akhq#1146]
Hey,

I experience an issue right after login to AKHQ in version 0.21.0. I have permission to view all topics and get an `null` error.
AKHQ shows that I have ~20 pages of topics. Some topics are quite large around 7 or 8 GB of data.

This is the screenshot

![akhq-error](https://user-images.githubusercontent.com/30616959/178237768-fccedc9b-b1a9-472a-903d-3c79de16c32c.jpg)

As you can see I have topics without consumers or a consumer which isn't active.

I get the following Java NullPointer error.

```
java.lang.NullPointerException: null
at org.akhq.repositories.AvroWireFormatConverter.convertValueToWireFormat(AvroWireFormatConverter.java:39)
	at org.akhq.repositories.RecordRepository.newRecord(RecordRepository.java:454)
	at org.akhq.repositories.RecordRepository.lambda$getLastRecord$3(RecordRepository.java:109)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.akhq.repositories.RecordRepository.getLastRecord(RecordRepository.java:107)
	at org.akhq.controllers.TopicController.lastRecord(TopicController.java:224)
	at org.akhq.controllers.$TopicController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:656)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Any Ideas on that? Thank you very much

**Comment by tchiotludo** [comment]
It's the last record cols that raise this error. 
It seems that you have a topic that akhq can't decode and failed [here](https://github.com/tchiotludo/akhq/blob/bf8c68eaba4bdba8bf865950e476eddb42f7a906/src/main/java/org/akhq/repositories/AvroWireFormatConverter.java#L39)
Maybe you can help on the topic that have this invalid data ? and provide the data ?

**Comment by wilkejo** [comment]
Thank you for the feedback.
What exactly do you mean with last record cols. Do you mean the last record or any record?

As we have a lot of topics and even more messages I don't have an idea how to identify the topic. Would it be possible to have an error message which identifies the topic, message Id? If I know which message it is, I could check if I can provide the data.

I don't know if it is relevant but we don't use avro schema. Sometimes we have no schema at all or if we have a schema we use json.

**Comment by wilkejo** [comment]
I recently update to 0.22 and still have the issue. If anyone could help me to narrow done the issue or find the invalid data.

I can reproduce the error if I try to look at topics and messages which use the json schema.

**Comment by wilkejo** [comment]
Hello @tchiotludo I did some further research and I'm quite sure, that my issue #1147 is related to #1035. 

I deployed AKHQ 0.22 and I can't read messages with tombstone records. Based on the description in #1035 I read the topic and looked for tombstones and found them. Also I got the confirmation from the producer, that tombstone records are written.

The first records of the topic look like this

```
AA:AA:TEXT1	null
AA:AA:TEXT2	null
```

Is this anything you can look into? Thanks

**Comment by tchiotludo** [comment]
It's fixed here I think https://github.com/tchiotludo/akhq/issues/1210

**Comment by wilkejo** [comment]
yes, 0.23 works really well
