### ISSUE TITLE
java.lang.RuntimeException: Error for Consume with options {}

### ISSUE THREAD

**Issue by wilkejo** [tchiotludo/akhq#1147]
Hey,

an error occurs for me when I try to read topic data from a topic with ≈ 34065151 messages and a size of 7.573 GB

I get this error. Any ideas?

```
java.lang.RuntimeException: Error for Consume with options {}
at org.akhq.utils.Debug.call(Debug.java:74)
	at org.akhq.repositories.RecordRepository.consume(RecordRepository.java:124)
	at org.akhq.controllers.TopicController.data(TopicController.java:205)
	at org.akhq.controllers.$TopicController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:656)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at org.akhq.repositories.AvroWireFormatConverter.convertValueToWireFormat(AvroWireFormatConverter.java:39)
	at org.akhq.repositories.RecordRepository.newRecord(RecordRepository.java:473)
	at org.akhq.repositories.RecordRepository.consumeOldest(RecordRepository.java:158)
	at org.akhq.repositories.RecordRepository.lambda$consume$4(RecordRepository.java:128)
	at org.akhq.utils.Debug.call(Debug.java:67)
	... 22 common frames omitted
```

**Comment by tchiotludo** [comment]
duplicate this one #1146
