### ISSUE TITLE
Apicurio registry : No version '2' found for artifact with ID 'com.company.movie' in group 'null'.; error code: 40402

### ISSUE THREAD

**Issue by mpumd** [tchiotludo/akhq#1198]
Hi tchiotludo,

I discover an issue when an artifact is disabled inside the apicurio registry. The rest API throw an exception like below : 

```
java.lang.RuntimeException: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: No version '2' found for artifact with ID 'com.company.movie' in group 'null'.; error code: 40402
	at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLatestVersion$1(SchemaRegistryRepository.java:55)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$SubList$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.akhq.repositories.SchemaRegistryRepository.toSchemasLatestVersion(SchemaRegistryRepository.java:58)
	at org.akhq.repositories.SchemaRegistryRepository.lambda$list$0(SchemaRegistryRepository.java:42)
	at org.akhq.utils.PagedList.of(PagedList.java:70)
	at org.akhq.repositories.SchemaRegistryRepository.list(SchemaRegistryRepository.java:42)
	at org.akhq.controllers.SchemaController.list(SchemaController.java:51)
	at org.akhq.controllers.$SchemaController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:351)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:656)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: No version '2' found for artifact with ID 'com.company.movie' in group 'null'.; error code: 40402
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:297)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:367)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:893)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getLatestVersion(RestService.java:884)
	at org.akhq.repositories.SchemaRegistryRepository.getLatestVersion(SchemaRegistryRepository.java:127)
	at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLatestVersion$1(SchemaRegistryRepository.java:53)
	... 32 common frames omitted
```

I saw you use confluent's dependencies inside your project, so you request apicurio by the compatibility api *ccompat*. Doesn't it ? 

Do we have any way to avoid showing the error banner, maybe get the previous valid version of the schema ? 
What do you think ?

Thanks in advance.

**Comment by mpusg** [comment]
Hi,

I investigate a little more and I discover an issue about the latest version of disabled schema. You can't get it with `/subjects/{subject}/versions/latest`. 
I created this issue https://github.com/Apicurio/apicurio-registry/issues/2790. 

I think you should avoid blocked the screen when the schema isn't available. 
you could sequentially call this following rest api I guess : 
GET ccompat/v6/subjects/ for list schema
GET ccompat/v6/subjects/com.company.movie/versions for list version => [1,2]

And try to get the last available version by managing the 404 error.
GET ccompat/v6/subjects/com.company.movie/versions/2 => 404 
GET ccompat/v6/subjects/com.company.movie/versions/1 => 200 OK

I think you have some methods inside the confluent lib related to this above endpoints.

**Comment by mpusg** [comment]
any news ?

**Comment by tchiotludo** [comment]
PR are welcome for this!

**Comment by vintech018** [comment]
I’ve opened a PR that handles disabled schema versions gracefully for Apicurio registry.  
Thanks!
