### ISSUE TITLE
Restart Container: java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by javier-torres** [tchiotludo/akhq#1214]
Hi,
We have these ERRORs during AKHQ is executing:

`Unexpected error occurred: Direct buffer memory
java.lang.OutOfMemoryError: Direct buffer memory
at java.base/java.nio.Bits.reserveMemory(Unknown Source)
at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:649)
at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:624)
at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:203)
at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:173)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
at io.netty.buffer.PoolArena.reallocate(PoolArena.java:287)
at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:122)
at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:305)
at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1073)
at io.netty.buffer.ByteBufOutputStream.write(ByteBufOutputStream.java:67)
at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171)`

There are times when the AKHQ container gets saturated by CPU and ends up giving memory errors. In our case we have it deployed in AWS Fargate and when this error happens it is not able to recover the container and stays dead. It would be possible to include in the logic of the process that after several attempts if it gives again the ERROR java.lang.OutOfMemoryError: Direct buffer memory to be able to exit the process so that AWS Fargate automatically throw the task and raise a new task. In many occasions this error happens to us, and we have to throw the FARGATE task manually to raise a new one.

If for some reason, to kill the process automatically after several attempts is not feasible, it would be interesting for the cases in which it is needed, to manage them by means of a variable as for example: OUT_OF_MEMORY_ERROR = "restart". So that you can automatically restart the container without having to do it manual

Thank you
Javier Torres

**Comment by tchiotludo** [comment]
Is this the same than this one ? https://github.com/tchiotludo/akhq/issues/1206

**Comment by tchiotludo** [comment]
closing due to inactivity, reopen if needed!
