### ISSUE TITLE
Healthcheck does not fail when threads are killed by exceptions

### ISSUE THREAD

**Issue by rouke-broersma** [tchiotludo/akhq#1375]
For example:

```
java.util.concurrent.ExecutionException: org.apache.kafka.common.KafkaException: Failed to find brokers to send ListGroups
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.kafka.common.KafkaException: Failed to find brokers to send ListGroups
	at org.akhq.controllers.GroupController.lambda$filterByTopics$0(GroupController.java:103)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.akhq.controllers.GroupController.filterByTopics(GroupController.java:98)
	at org.akhq.controllers.$GroupController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:77)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:162)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.KafkaException: Failed to find brokers to send ListGroups
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
	at org.akhq.utils.Logger.call(Logger.java:44)
	at org.akhq.modules.AbstractKafkaWrapper.listConsumerGroups(AbstractKafkaWrapper.java:169)
	at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Intercepted.listConsumerGroups(Unknown Source)
	at org.akhq.repositories.ConsumerGroupRepository.all(ConsumerGroupRepository.java:48)
	at org.akhq.repositories.ConsumerGroupRepository.findByTopics(ConsumerGroupRepository.java:125)
	at org.akhq.controllers.GroupController.lambda$filterByTopics$0(GroupController.java:101)
	... 22 common frames omitted
Caused by: org.apache.kafka.common.KafkaException: Failed to find brokers to send ListGroups
	at org.apache.kafka.clients.admin.KafkaAdminClient$24.handleFailure(KafkaAdminClient.java:3395)
	at org.apache.kafka.clients.admin.KafkaAdminClient$Call.handleTimeoutFailure(KafkaAdminClient.java:853)
	at org.apache.kafka.clients.admin.KafkaAdminClient$Call.access$2100(KafkaAdminClient.java:745)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.enqueue(KafkaAdminClient.java:1459)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.call(KafkaAdminClient.java:1478)
	at org.apache.kafka.clients.admin.KafkaAdminClient.listConsumerGroups(KafkaAdminClient.java:3322)
	at org.apache.kafka.clients.admin.Admin.listConsumerGroups(Admin.java:914)
	at org.akhq.modules.AbstractKafkaWrapper.listConsumerGroups(AbstractKafkaWrapper.java:170)
	... 29 common frames omitted
Caused by: org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited.
```

The UI then shows this message: 
![image](https://user-images.githubusercontent.com/3595932/218677077-5443ac5b-1aa5-4dc9-9dfb-c9cf65bc6cce.png)

However the pods report as being perfectly happy: 
![image](https://user-images.githubusercontent.com/3595932/218677340-8296172e-48eb-4737-8e22-0609b751c41c.png)

A restart of the pod fixes the issue. Kafka also isn't unavailable, it's only akhq having trouble reconnecting (probably because the background thread that's supposed to do this has crashed and is not restarting).

Functioning health checks would have us back online, now we have to manually restart the pods. We are using your helm chart, are we missing some configuration option to make the health check behave in the expected manner?

**Comment by tchiotludo** [comment]
The best will be to implement either : 
- a [custom healthcheck](https://guides.micronaut.io/latest/micronaut-health-endpoint-gradle-java.html) in micronaut for that check the kafka connectivity 
- a [scheduled task](https://docs.micronaut.io/latest/guide/index.html#scheduling) to close and restart the admin client 
PR are welcome

**Comment by rouke-broersma** [comment]
@tchiotludo I'm not much of a Java developer, but shouldn't this exception simply crash the application since there's currently no way akhq recovers from this?

**Comment by kapilgahlot1998** [comment]
@tchiotludo I am assuming this issue is still not fixed as this issue is still open. I will start analyzing the issue and the approaches mentioned in the earlier comments. 
Let me know if anything other things needs to taken care.

Thanks

**Comment by Amir-Golmoradi** [comment]
Hey there Mr @tchiotludo , if you allow me I'd love to take on this issue. Could you assign it to me?

**Comment by tchiotludo** [comment]
it's for you @Amir-Golmoradi, thanks a lot

**Comment by Saikrishna8639** [comment]
Hi @Amir-Golmoradi , Any updates on the resolution for this issue?
We are currently encountering the same behaviour in our production environment — the AKHQ pod remains in a running state, but we observe continuous logs below and unable to open AKHQ UI with Pop up as **AdminClient thread has exited **

2025-06-10 09:51:57,098 [1;31mERROR[0;39m [35mio-executor-thread-358[0;39m [36mo.akhq.controllers.ErrorController[0;39m **Error for Describe Topic Config** {}
java.lang.RuntimeException: Error for Describe Topic Config {}
	at org.akhq.utils.Logger.call(Logger.java:31)
	at org.akhq.modules.AbstractKafkaWrapper.describeConfigs(AbstractKafkaWrapper.java:332)
	at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:456)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:129)
	at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Intercepted.describeConfigs(Unknown Source)
	at org.akhq.repositories.ConfigRepository.find(ConfigRepository.java:47)
	at org.akhq.repositories.ConfigRepository.findByTopics(ConfigRepository.java:41)
	at org.akhq.repositories.ConfigRepository.findByTopic(ConfigRepository.java:37)
	at org.akhq.controllers.TopicController.config(TopicController.java:291)
	at org.akhq.controllers.$TopicController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)
	at io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4276)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:236)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:488)
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:465)
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:193)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.kafka.common.errors.TimeoutException: **The AdminClient thread has exited.**
2025-06-10 09:51:57,099 [31mWARN [0;39m [35mio-executor-thread-358[0;39m [36morg.akhq.log.access[0;39m [Date: 2025-06-10T09:51:57.097212167Z] [Duration: 1 ms] [Url: GET /api/kafka-east-prod/topic/app.fm.cal-milestone.milestone/configs] [Status: 500] [Ip: /10.233.108.73] [User: timmidib]

Currently, we are using **tchiotludo/akhq:0.25.1** image in our PROD. 
Please advise if there’s a known fix or recommended workaround to this issue.

thanks & regards,
