### ISSUE TITLE
 Issues selecting serialization schema in AKHQ (SSLHandshakeException)

### ISSUE THREAD

**Issue by carlosfwrk** [tchiotludo/akhq#1440]
**Description**
The AKHQ client works correctly in all functionalities, such as viewing topics, messages, and consumer groups. However, when producing a message to the topic, the dropdown to select the key/value serialization schema takes between 5-10 minutes to appear. Additionally, in some instances, an SSLHandshakeException error appears.

**Steps to reproduce**
Select the desired topic
Click on the _"Produce message"_ button
Wait for the dropdown to appear to select the key/value schema
In some instances, an SSLHandshakeException error or connect time out error appears.

**Expected behavior**
The dropdown to select the key/value serialization schema should appear in a few seconds and without any SSLHandshakeException errors.

**Current behavior**
The dropdown takes between 5-10 minutes to appear, during this time, several errors occur, including `Ignoring invalid logical type for name: date`. 
Additionally, sometimes `timeout `errors occur, although the schemas eventually appear. 
On some occasions, the process is interrupted with an `SSLHandshakeException` error. 

**AKHQ Configuration**
```
akhq:
  connections:
    kafka:
      properties:
        bootstrap.servers: "kafka-server:443"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${USERNAME}" password="${PASSWORD}";
        ssl.truststore.location: /app/ca/truststore.jks
        ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
      schema-registry:
        url: "https://schemaregistry-url.com"
        type: "confluent"
        basic-auth-username: ${USERNAME}
        basic-auth-password: ${PASSWORD}
        properties:
          schema.registry.ssl.truststore.location: /app/ca/truststore.jks
          schema.registry.ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
          schema.registry.ssl.protocol: TLS
          schema.registry.ssl.keystore.location: /app/ca/truststore.jks
          schema.registry.ssl.keystore.password: ${TRUSTSTORE_PASSWORD} 
```
**AKHQ version**: 0.23.0

**LOG that writes during that 5-10 minutes (at the end I can produce correctly the record)**
```
2023-03-29 12:57:10 2023-03-29 10:57:10,703 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 12:57:10 2023-03-29 10:57:10,810 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 12:57:11 2023-03-29 10:57:11,210 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 12:57:11 2023-03-29 10:57:11,303 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 12:57:13 2023-03-29 10:57:13,273 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 12:57:13 2023-03-29 10:57:13,366 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 12:58:54 2023-03-29 10:58:54,933 ERROR r-thread-4 c.k.s.a.AvroSchemaProvider Could not parse Avro schema
2023-03-29 12:58:54 java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getByVersion(CachedSchemaRegistryClient.java:472)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.AbstractSchemaProvider.resolveReferences(AbstractSchemaProvider.java:60)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.AbstractSchemaProvider.resolveReferences(AbstractSchemaProvider.java:47)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.avro.AvroSchemaProvider.parseSchemaOrElseThrow(AvroSchemaProvider.java:53)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.SchemaProvider.parseSchema(SchemaProvider.java:77)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.SchemaProvider.parseSchema(SchemaProvider.java:86)
2023-03-29 12:58:54     at org.akhq.repositories.SchemaRegistryRepository.getParsedSchema(SchemaRegistryRepository.java:77)
2023-03-29 12:58:54     at org.akhq.repositories.SchemaRegistryRepository.getLatestVersion(SchemaRegistryRepository.java:129)
2023-03-29 12:58:54     at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLatestVersion$1(SchemaRegistryRepository.java:53)
2023-03-29 12:58:54     at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
2023-03-29 12:58:54     at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
2023-03-29 12:58:54     at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
2023-03-29 12:58:54     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
2023-03-29 12:58:54     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
2023-03-29 12:58:54     at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
2023-03-29 12:58:54     at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
2023-03-29 12:58:54     at org.akhq.repositories.SchemaRegistryRepository.toSchemasLatestVersion(SchemaRegistryRepository.java:58)
2023-03-29 12:58:54     at org.akhq.repositories.SchemaRegistryRepository.listAll(SchemaRegistryRepository.java:46)
2023-03-29 12:58:54     at org.akhq.controllers.SchemaController.listSchemaForTopic(SchemaController.java:61)
2023-03-29 12:58:54     at org.akhq.controllers.$SchemaController$Definition$Exec.dispatch(Unknown Source)
2023-03-29 12:58:54     at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
2023-03-29 12:58:54     at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
2023-03-29 12:58:54     at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
2023-03-29 12:58:54     at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
2023-03-29 12:58:54     at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
2023-03-29 12:58:54     at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
2023-03-29 12:58:54     at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
2023-03-29 12:58:54     at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
2023-03-29 12:58:54     at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
2023-03-29 12:58:54     at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
2023-03-29 12:58:54     at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
2023-03-29 12:58:54     at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
2023-03-29 12:58:54     at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
2023-03-29 12:58:54     at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:77)
2023-03-29 12:58:54     at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:162)
2023-03-29 12:58:54     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2023-03-29 12:58:54     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-03-29 12:58:54     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-03-29 12:58:54     at java.base/java.lang.Thread.run(Unknown Source)
2023-03-29 12:58:54 Caused by: java.net.SocketTimeoutException: connect timed out
2023-03-29 12:58:54     at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
2023-03-29 12:58:54     at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
2023-03-29 12:58:54     at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
2023-03-29 12:58:54     at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
2023-03-29 12:58:54     at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
2023-03-29 12:58:54     at java.base/java.net.Socket.connect(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
2023-03-29 12:58:54     at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
2023-03-29 12:58:54     at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:282)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:372)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.client.rest.RestService.getVersion(RestService.java:899)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.client.rest.RestService.getVersion(RestService.java:883)
2023-03-29 12:58:54     at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getByVersion(CachedSchemaRegistryClient.java:470)
2023-03-29 12:58:54     ... 38 common frames omitted
2023-03-29 12:59:10 2023-03-29 10:59:10,391 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 12:59:10 2023-03-29 10:59:10,493 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 13:00:09 2023-03-29 11:00:09,223 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 13:00:09 2023-03-29 11:00:09,336 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 13:00:09 2023-03-29 11:00:09,851 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 13:00:09 2023-03-29 11:00:09,962 WARN  r-thread-4 o.apache.avro.LogicalTypes Ignoring invalid logical type for name: date
2023-03-29 13:03:48 2023-03-29 11:03:48,950 INFO  r-thread-6 org.akhq.log.access        [Date: 2023-03-29T10:56:35.989552Z] [Duration: 432960 ms] [Url: GET /api/kafka-dev/schema/topic/apps.kafka.demo1.event.private.v0.application.cpd] [Status: 200] [Ip: /10.10.0.1] [User: -]
2023-03-29 13:03:49 2023-03-29 11:03:49,582 INFO  r-thread-6 org.akhq.log.access        [Date: 2023-03-29T11:03:49.251029Z] [Duration: 330 ms] [Url: GET /api/kafka-dev/topic] [Status: 200] [Ip: /10.10.0.1] [User: -]
```
**Sometimes stop trying and I can't produce because of the following error**
```
ERROR -thread-15 o.a.c.ErrorController      javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
```

**Comment by carlosfwrk** [comment]
To add more details, in my current environment, I have over 1100 schemas, but I have noticed that from the Schema Registry section, the load times are quite good, taking only about 10 seconds.

**Comment by carlosfwrk** [comment]
Hi @tchiotludo, 
I've tested the version on the dev branch, and schema loading on the serialized message producer screen is working perfectly. Thank you very much for addressing this; it's working great now.

However, starting from version 0.24.0 (which wasn't an issue in, for example, version 0.21.0), when it displays the messages, it deserializes the values perfectly but throws an error when deserializing the key. Do you know if this part might have been "broken," or if I need to add something to the configuration for it to display correctly? 
The strange thing is that the same configuration displays correctly in 0.21.0 but not in 0.24.0 and later.

This is the error:
![image](https://github.com/tchiotludo/akhq/assets/129170393/bf0f0875-bf2c-47b0-8f08-adb721ce5b93)

These are the logs that appear while loading the messages:
``` shell
2023-09-15 13:33:24,342 DEBUG -thread-22 org.akhq.utils.Logger      7 ms -> Describe Topics [apps.kafkatest.pruebas.event.private.v0.application.cpd]
2023-09-15 13:33:24,342 DEBUG -thread-17 org.akhq.utils.Logger      6 ms -> Describe Topics [apps.kafkatest.pruebas.event.private.v0.application.cpd]
2023-09-15 13:33:24,342 DEBUG -thread-21 org.akhq.utils.Logger      8 ms -> Describe Topic Config [apps.kafkatest.pruebas.event.private.v0.application.cpd]
2023-09-15 13:33:24,344 INFO  -thread-20 org.akhq.log.access        [Date: 2023-09-15T13:33:24.331208Z] [Duration: 13 ms] [Url: GET /api/kafka-dev/topic/apps.kafkatest.pruebas.event.private.v0.application.cpd/configs] [Status: 200] [Ip: /172.17.0.1] [User: -]
2023-09-15 13:33:24,537 DEBUG -thread-22 org.akhq.utils.Logger      195 ms -> Describe Topics Offsets [apps.kafkatest.pruebas.event.private.v0.application.cpd]
2023-09-15 13:33:24,542 DEBUG -thread-17 org.akhq.utils.Logger      200 ms -> Describe Topics Offsets [apps.kafkatest.pruebas.event.private.v0.application.cpd]
2023-09-15 13:33:24,543 DEBUG -thread-22 org.akhq.utils.Logger      6 ms -> Get cluster
2023-09-15 13:33:24,543 DEBUG -thread-22 org.akhq.utils.Logger      0 ms -> Get nodes
2023-09-15 13:33:24,543 DEBUG -thread-22 org.akhq.utils.Logger      0 ms -> Get contoller
2023-09-15 13:33:24,547 DEBUG -thread-17 org.akhq.utils.Logger      4 ms -> Get cluster
2023-09-15 13:33:24,548 DEBUG -thread-17 org.akhq.utils.Logger      0 ms -> Get nodes
2023-09-15 13:33:24,548 DEBUG -thread-17 org.akhq.utils.Logger      0 ms -> Get contoller
2023-09-15 13:33:24,552 DEBUG -thread-22 org.akhq.utils.Logger      15 ms -> List Log dir
2023-09-15 13:33:24,559 TRACE -thread-22 o.a.r.RecordRepository     Consume Newest [topic: apps.kafkatest.pruebas.event.private.v0.application.cpd] [partition: 1] [start: 366363]
2023-09-15 13:33:24,559 TRACE -worker-11 o.a.r.RecordRepository     Consume Newest [topic: apps.kafkatest.pruebas.event.private.v0.application.cpd] [partition: 0] [start: 85]
2023-09-15 13:33:24,560 DEBUG -thread-17 org.akhq.utils.Logger      17 ms -> List Log dir
2023-09-15 13:33:24,561 INFO  -thread-20 org.akhq.log.access        [Date: 2023-09-15T13:33:24.335412Z] [Duration: 225 ms] [Url: GET /api/kafka-dev/topic/apps.kafkatest.pruebas.event.private.v0.application.cpd/partitions] [Status: 200] [Ip: /172.17.0.1] [User: -]
2023-09-15 13:33:24,734 TRACE -worker-11 o.a.r.RecordRepository     Empty pool [topic: apps.kafkatest.pruebas.event.private.v0.application.cpd] [partition: 0]
2023-09-15 13:33:24,734 TRACE -worker-11 o.akhq.utils.MaskingUtils  masking record
2023-09-15 13:33:24,803 TRACE -worker-11 o.akhq.utils.MaskingUtils  masking record
2023-09-15 13:33:25,742 DEBUG -thread-22 o.a.r.RecordRepository     1189 ms -> Consume with options [RecordRepository.Options(topic=apps.kafkatest.pruebas.event.private.v0.application.cpd, size=50, after={}, sort=NEWEST, partition=null, timestamp=null)]
2023-09-15 13:33:25,749 DEBUG -thread-22 org.akhq.utils.Logger      7 ms -> Describe Topic Config [apps.kafkatest.pruebas.event.private.v0.application.cpd]
2023-09-15 13:33:25,751 INFO  -thread-20 org.akhq.log.access        [Date: 2023-09-15T13:33:24.33174Z] [Duration: 1419 ms] [Url: GET /api/kafka-dev/topic/apps.kafkatest.pruebas.event.private.v0.application.cpd/data] [Status: 200] [Ip: /172.17.0.1] [User: -]
```

This is the configuration.yml content:
``` yaml
akhq:
  server:
    access-log:
      enabled: true
      name: org.akhq.log.access
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]"
  connections:
    kafka-dev:
      properties:
        bootstrap.servers: "bootstrap.kafka.dev.com:443"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${USERNAME}" password="${PASSWORD}";
        ssl.truststore.location: /app/ca/cacerts.jks
        ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
      schema-registry:
        url: "https://schemaregistry.dev.com"
        type: "confluent"
        basic-auth-username: ${USERNAME}
        basic-auth-password: ${PASSWORD}
        properties:
          schema.registry.ssl.truststore.location: /app/ca/cacerts.jks
          schema.registry.ssl.truststore.password: ${TRUSTSTORE_PASSWORD}
```

Thanks.

**Comment by carlosfwrk** [comment]
I'm sorry, I wanted to thank you for the great job in resolving the issue with producing serialized messages, but I got off-topic. I have opened a new issue for this other question --> #1573
