### ISSUE TITLE
SSLHandshakeException when trying to connect with confluent cloud schema registry

### ISSUE THREAD

**Issue by stratos-zopa** [tchiotludo/akhq#1452]
Hi,
when trying to connect with a confluent cloud schema registry, the application fails with an SSLHandshakeException. More specifically, I'm using the following configuration (I've also tried removing the double quotes around the secrets)
```
akhq:
  connections:
    kafka-server:
      properties:
        bootstrap.servers: "???.confluent.cloud:9092"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="???" password="???";
      schema-registry:
        url: "https://???.confluent.cloud"
        basic-auth-username: "???"
        basic-auth-password: "???"
```
It looks identical with the documentation https://akhq.io/docs/configuration/brokers.html#example-for-confluent-cloud.
Note, that akhq connects fine with the confluent cloud cluster.

Am I missing something in the config or is this a genuine issue in akhq?

The stack trace of the error is:
```2023-04-04 15:33:17,272 ERROR r-thread-5 o.a.c.ErrorController      PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2023-04-04T15:33:17.274507590Z javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2023-04-04T15:33:17.274578797Z  at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
2023-04-04T15:33:17.274587325Z  at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
2023-04-04T15:33:17.274591781Z  at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
2023-04-04T15:33:17.274595988Z  at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
2023-04-04T15:33:17.274599733Z  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
2023-04-04T15:33:17.274604051Z  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
2023-04-04T15:33:17.274607933Z  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
2023-04-04T15:33:17.274638371Z  at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
2023-04-04T15:33:17.274646790Z  at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
2023-04-04T15:33:17.274651323Z  at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
2023-04-04T15:33:17.274675580Z  at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
2023-04-04T15:33:17.274681662Z  at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
2023-04-04T15:33:17.274686049Z  at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
2023-04-04T15:33:17.274689817Z  at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
2023-04-04T15:33:17.274693357Z  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
2023-04-04T15:33:17.274696744Z  at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
2023-04-04T15:33:17.274700536Z  at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
2023-04-04T15:33:17.274704129Z  at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
2023-04-04T15:33:17.274708177Z  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
2023-04-04T15:33:17.274712587Z  at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
2023-04-04T15:33:17.274719512Z  at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
2023-04-04T15:33:17.274724223Z  at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
2023-04-04T15:33:17.274728251Z  at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:282)
2023-04-04T15:33:17.274731846Z  at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:372)
2023-04-04T15:33:17.274735471Z  at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:1016)
2023-04-04T15:33:17.274738949Z  at io.confluent.kafka.schemaregistry.client.rest.RestService.getAllSubjects(RestService.java:1001)
2023-04-04T15:33:17.274743056Z  at org.akhq.repositories.SchemaRegistryRepository.all(SchemaRegistryRepository.java:90)
2023-04-04T15:33:17.274747058Z  at org.akhq.repositories.SchemaRegistryRepository.list(SchemaRegistryRepository.java:42)
2023-04-04T15:33:17.274751084Z  at org.akhq.controllers.SchemaController.list(SchemaController.java:51)
2023-04-04T15:33:17.274754872Z  at org.akhq.controllers.$SchemaController$Definition$Exec.dispatch(Unknown Source)
2023-04-04T15:33:17.274758976Z  at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
2023-04-04T15:33:17.274763479Z  at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
2023-04-04T15:33:17.274767663Z  at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
2023-04-04T15:33:17.274771603Z  at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
2023-04-04T15:33:17.274775646Z  at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
2023-04-04T15:33:17.274779462Z  at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
2023-04-04T15:33:17.274792650Z  at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
2023-04-04T15:33:17.274797730Z  at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
2023-04-04T15:33:17.274801476Z  at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
2023-04-04T15:33:17.274813442Z  at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
2023-04-04T15:33:17.274817299Z  at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
2023-04-04T15:33:17.274820606Z  at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
2023-04-04T15:33:17.274825654Z  at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:77)
2023-04-04T15:33:17.274830212Z  at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:162)
2023-04-04T15:33:17.274834215Z  at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
2023-04-04T15:33:17.274838379Z  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2023-04-04T15:33:17.274842146Z  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-04-04T15:33:17.274846040Z  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-04-04T15:33:17.274849923Z  at java.base/java.lang.Thread.run(Unknown Source)
2023-04-04T15:33:17.274854000Z Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2023-04-04T15:33:17.274858385Z  at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
2023-04-04T15:33:17.274861119Z  at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
2023-04-04T15:33:17.274863455Z  at java.base/sun.security.validator.Validator.validate(Unknown Source)
2023-04-04T15:33:17.274865734Z  at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
2023-04-04T15:33:17.274868015Z  at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
2023-04-04T15:33:17.274870354Z  at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
2023-04-04T15:33:17.274872665Z  ... 45 common frames omitted
2023-04-04T15:33:17.274874966Z Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2023-04-04T15:33:17.274877412Z  at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
2023-04-04T15:33:17.274879720Z  at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
2023-04-04T15:33:17.274882052Z  at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
```

**Comment by stratos-zopa** [comment]
Please ignore - this was an issue with not passing the right certificates to the image. Connection is working fine.
