### ISSUE TITLE
The issues happened when I want to login the page by google,

### ISSUE THREAD

**Issue by sleepwinter** [tchiotludo/akhq#1510]
```
react-dom.production.min.js:209 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at nc (react-dom.production.min.js:230:46)
    at Object.enqueueSetState (react-dom.production.min.js:132:237)
    at w.setState (react.production.min.js:12:369)
    at Router.js:34:16
    at r (history.js:155:24)
    at history.js:173:23
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (history.js:172:15)
    at g (history.js:288:23)
    at history.js:369:11
```

**Comment by sleepwinter** [comment]
This error only occurs when I set "default-group: no-roles".

**Comment by tchiotludo** [comment]
everything have been rewrite on #1472, can you try with latest dev version and reopen if it's not working ?
