### ISSUE TITLE
AKHQ 0.24.0: Consumer Group doesn't exist due to @ character in group name

### ISSUE THREAD

**Issue by AdiWehrli** [tchiotludo/akhq#1530]
We use the `@` character in consumer group names. The listing of consumer groups works but if you want to open the details view for a specific group, the view is empty and in the log the following stacktrace is shown:
```
2023-07-11T05:41:12.209 level=ERROR thread=io-executor-thread-3 releaseVersion=0.24.0 logger=org.akhq.controllers.ErrorController msg="Consumer Group 'principal%40test-consumer' doesn't exist"
java.util.NoSuchElementException: Consumer Group 'principal%40test-consumer' doesn't exist
        at org.akhq.repositories.ConsumerGroupRepository.lambda$findByName$1(ConsumerGroupRepository.java:65)
        at java.base/java.util.Optional.orElseThrow(Unknown Source)
        at org.akhq.repositories.ConsumerGroupRepository.findByName(ConsumerGroupRepository.java:65)
        at org.akhq.controllers.GroupController.offsets(GroupController.java:79)
        at org.akhq.controllers.$GroupController$Definition$Exec.dispatch(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
        at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
        at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:206)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

So it seems, that the character `@` is replaced by its HTML entity `%40` in the details link, which causes the consumer group not to be found.

If I copy the link for details view and replace the `%40` by `@` again then it works.

Thanks and best regards,
Adi

**Comment by tchiotludo** [comment]
I think it's fixed on `dev` by this [commit](https://github.com/tchiotludo/akhq/commit/8ddb9cb7ebc1d073a1d854087b57583dd26216ed), reopen if not please
