### ISSUE TITLE
KSQL supports : No value present

### ISSUE THREAD

**Issue by alcudiaMV** [tchiotludo/akhq#1635]
Hi,

I have deployed version 0.24, ksqldb is available with this configuration :

   
    connections:
           xx-hp-00:
              properties:
                bootstrap.servers: "..."
                security.protocol: SASL_SSL
                sasl.mechanism: PLAIN
                sasl.jaas.config: ${AKHQ_SASL_JAAS_CONFIG}
                ssl.truststore.location: /usr/local/share/xxxxx.jks
                ssl.truststore.password: ${PASSWORD}
              ksqldb:
                - name: "ksql402"
                  useTLS: true
                  url: "https://ksql402xxxxxxx"
                  basic-auth-username: "xxxx"
                  basic-auth-password: "xxxxx"
             

      security:
        roles:
          ...
          groups:
            admin:
              roles:
                - ksqldb/read
                - ksqldb/execute
   

 But when I click on the instance I got an error :  

    2023-12-19 15:56:34,420 ERROR -thread-13 o.a.c.ErrorController      No value present
    67
    java.util.NoSuchElementException: No value present
    66
	    at java.base/java.util.Optional.get(Unknown Source)
    65
	    at org.akhq.modules.KafkaModule.lambda$getKsqlDbClient$7(KafkaModule.java:363)
    64
	    at java.base/java.util.ArrayList.forEach(Unknown Source)
    63
	    at org.akhq.modules.KafkaModule.getKsqlDbClient(KafkaModule.java:357)
    62
	    at org.akhq.repositories.KsqlDbRepository.listStreams(KsqlDbRepository.java:60)
    61
	    at org.akhq.repositories.KsqlDbRepository.getPaginatedStreams(KsqlDbRepository.java:48)
    60
	    at org.akhq.repositories.$KsqlDbRepository$Definition$Intercepted.$$access$$getPaginatedStreams(Unknown Source)
    59
	    at org.akhq.repositories.$KsqlDbRepository$Definition$Exec.dispatch(Unknown Source)
    58
	    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
    57
	    at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
    56
	    at io.micronaut.aop.internal.intercepted.SynchronousInterceptedMethod.interceptResult(SynchronousInterceptedMethod.java:55)
    55
	    at io.micronaut.retry.intercept.DefaultRetryInterceptor.retrySync(DefaultRetryInterceptor.java:216)
    54
	    at io.micronaut.retry.intercept.DefaultRetryInterceptor.intercept(DefaultRetryInterceptor.java:123)
    53
	    at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
    52
	    at org.akhq.repositories.$KsqlDbRepository$Definition$Intercepted.getPaginatedStreams(Unknown Source)
    51
	    at org.akhq.controllers.KsqlDbController.listStreams(KsqlDbController.java:48)
    50
	    at org.akhq.controllers.$KsqlDbController$Definition$Exec.dispatch(Unknown Source)
    49
	    at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
    48
	    at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
    47
	    at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
    46
	    at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
    45
	    at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
    44
	    at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
    43
	    at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
    42
	    at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
    41
	    at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
    40
	    at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
    39
	    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
    38
	    at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
    37
	    at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
    36
	    at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
    35
	    at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:206)
    34
	    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    33
	    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    32
	    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    31
	    at java.base/java.lang.Thread.run(Unknown Source)

If you have a sugestion :-)

Thanks

**Comment by alcudiaMV** [comment]
The root cause is the format of my url : "https://ksql402xxxxxxx"
An url without port for KSQL can't to work with the AKHQ code version 0.24.0:

Class org.akhq.modules.KafkaModule  line 363

     private final Map<String, Map<String, Client>> ksqlDbClient = new HashMap<>();
    public Map<String, Client> getKsqlDbClient(String clusterId) throws InvalidClusterException {
        if (!this.clusterExists(clusterId)) {
            throw new InvalidClusterException("Invalid cluster '" + clusterId + "'");
        }

        if (!this.ksqlDbClient.containsKey(clusterId)) {
            Connection connection = this.getConnection(clusterId);

            if (connection.getKsqldb() != null && !connection.getKsqldb().isEmpty()) {
                Map<String, Client> mapKsqlDbs = new HashMap<>();
                connection.getKsqldb().forEach(ksqlDb -> {

                    URIBuilder uri = URIBuilder.fromString(ksqlDb.getUrl().toString());

                    ClientOptions options = ClientOptions.create()
                        .setHost(uri.getHost().get())
                        **.setPort(uri.getPort().get())**
                        .setUseTls(ksqlDb.isUseTls())
                        .setUseAlpn(ksqlDb.isUseAlpn())
                        .setVerifyHost(ksqlDb.isVerifyHost());
                    if (ksqlDb.getBasicAuthUsername() != null && ksqlDb.getBasicAuthPassword() != null) {
                        options.setBasicAuthCredentials(ksqlDb.getBasicAuthUsername(), ksqlDb.getBasicAuthPassword());
                    }
                    Client client = Client.create(options);

                    mapKsqlDbs.put(ksqlDb.getName(), client);
                });
                this.ksqlDbClient.put(clusterId, mapKsqlDbs);
            }
        }

        return this.ksqlDbClient.get(clusterId);
    }
}

**Comment by aonamrata** [comment]
What is the solution to this? I tried `  https://ksql402xxxxxxx:443` and it gave me a diff error
```
on: 10505 ms] [Url: GET /api/docker-kafka-server/topic/last-record] [Status: 200] [Ip: /172.18.0.1] [User: -]
2024-03-01 16:27:05 2024-03-01 10:57:05,739 ERROR p-thread-1 i.v.core.impl.ContextBase  Unhandled exception
2024-03-01 16:27:05 java.lang.NullPointerException: null
2024-03-01 16:27:05     at io.confluent.ksql.api.client.impl.ClientImpl.handleSingleEntityResponse(ClientImpl.java:832)
2024-03-01 16:27:05     at io.confluent.ksql.api.client.impl.ClientImpl.handleSingleEntityResponse(ClientImpl.java:821)
2024-03-01 16:27:05     at io.confluent.ksql.api.client.impl.ClientImpl.lambda$listStreams$8(ClientImpl.java:279)
2024-03-01 16:27:05     at io.confluent.ksql.api.client.impl.ClientImpl.lambda$null$27(ClientImpl.java:751)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
2024-03-01 16:27:05     at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
2024-03-01 16:27:05     at io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:165)
2024-03-01 16:27:05     at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:160)
2024-03-01 16:27:05     at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:77)
2024-03-01 16:27:05     at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.handleException(Http2ClientConnection.java:493)
2024-03-01 16:27:05     at io.vertx.core.http.impl.Http2ConnectionBase.lambda$onConnectionError$1(Http2ConnectionBase.java:120)
2024-03-01 16:27:05     at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
2024-03-01 16:27:05     at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
2024-03-01 16:27:05     at io.vertx.core.http.impl.Http2ConnectionBase.onConnectionError(Http2ConnectionBase.java:120)
2024-03-01 16:27:05     at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.onConnectionError(VertxHttp2ConnectionHandler.java:159)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:656)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.error(DefaultHttp2ConnectionEncoder.java:467)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledBase.operationComplete(DefaultHttp2ConnectionEncoder.java:630)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledBase.operationComplete(DefaultHttp2ConnectionEncoder.java:604)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryPromise(Http2CodecUtil.java:385)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryFailure(Http2CodecUtil.java:306)
2024-03-01 16:27:05     at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
2024-03-01 16:27:05     at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:733)
2024-03-01 16:27:05     at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:318)
2024-03-01 16:27:05     at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:670)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:735)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannel$AbstractUnsafe.handleWriteError(AbstractChannel.java:950)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:933)
2024-03-01 16:27:05     at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
2024-03-01 16:27:05     at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:197)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
2024-03-01 16:27:05     at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
2024-03-01 16:27:05     at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.writeData(VertxHttp2ConnectionHandler.java:237)
2024-03-01 16:27:05     at io.vertx.core.http.impl.VertxHttp2Stream.doWriteData(VertxHttp2Stream.java:223)
2024-03-01 16:27:05     at io.vertx.core.http.impl.Http2ClientConnection$Stream.doWriteData(Http2ClientConnection.java:257)
2024-03-01 16:27:05     at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.writeHeaders(Http2ClientConnection.java:543)
2024-03-01 16:27:05     at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.lambda$writeHead$0(Http2ClientConnection.java:501)
2024-03-01 16:27:05     at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
2024-03-01 16:27:05     at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
2024-03-01 16:27:05     at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.writeHead(Http2ClientConnection.java:500)
2024-03-01 16:27:05     at io.vertx.core.http.impl.HttpClientRequestImpl.doWrite(HttpClientRequestImpl.java:476)
2024-03-01 16:27:05     at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:449)
2024-03-01 16:27:05     at io.vertx.core.http.impl.HttpClientRequestImpl.end(HttpClientRequestImpl.java:377)
2024-03-01 16:27:05     at io.confluent.ksql.api.client.impl.ClientImpl.lambda$makeRequest$29(ClientImpl.java:768)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
2024-03-01 16:27:05     at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
2024-03-01 16:27:05     at io.vertx.core.http.impl.HttpClientImpl.lambda$null$5(HttpClientImpl.java:652)
2024-03-01 16:27:05     at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
2024-03-01 16:27:05     at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
2024-03-01 16:27:05     at io.vertx.core.http.impl.Http2ClientConnection.createStream(Http2ClientConnection.java:153)
2024-03-01 16:27:05     at io.vertx.core.http.impl.HttpClientImpl.lambda$doRequest$6(HttpClientImpl.java:635)
2024-03-01 16:27:05     at io.vertx.core.net.impl.pool.Endpoint.lambda$getConnection$0(Endpoint.java:52)
2024-03-01 16:27:05     at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:162)
2024-03-01 16:27:05     at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:123)
2024-03-01 16:27:05     at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
2024-03-01 16:27:05     at io.vertx.core.impl.ContextBase.emit(ContextBase.java:239)
2024-03-01 16:27:05     at io.vertx.core.net.impl.pool.SimpleConnectionPool$LeaseImpl.emit(SimpleConnectionPool.java:704)
2024-03-01 16:27:05     at io.vertx.core.net.impl.pool.SimpleConnectionPool$ConnectSuccess$2.run(SimpleConnectionPool.java:338)
2024-03-01 16:27:05     at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:50)
2024-03-01 16:27:05     at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:245)
2024-03-01 16:27:05     at io.vertx.core.net.impl.pool.SimpleConnectionPool.lambda$connect$2(SimpleConnectionPool.java:257)
2024-03-01 16:27:05     at io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.lambda$connect$2(SharedClientHttpStreamEndpoint.java:102)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
2024-03-01 16:27:05     at io.vertx.core.impl.future.Composition$1.onSuccess(Composition.java:62)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
2024-03-01 16:27:05     at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:86)
2024-03-01 16:27:05     at io.vertx.core.impl.ContextBase.execute(ContextBase.java:225)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
2024-03-01 16:27:05     at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211)
2024-03-01 16:27:05     at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
2024-03-01 16:27:05     at io.vertx.core.Promise.complete(Promise.java:66)
2024-03-01 16:27:05     at io.vertx.core.impl.future.PromiseImpl.operationComplete(PromiseImpl.java:65)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
2024-03-01 16:27:05     at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:97)
2024-03-01 16:27:05     at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.onSettingsRead(VertxHttp2ConnectionHandler.java:390)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onSettingsRead(Http2FrameListenerDecorator.java:69)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:515)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:735)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readSettingsFrame(DefaultHttp2FrameReader.java:532)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:262)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:250)
2024-03-01 16:27:05     at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
2024-03-01 16:27:05     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
2024-03-01 16:27:05     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
2024-03-01 16:27:05     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
2024-03-01 16:27:05     at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelRead(VertxHttp2ConnectionHandler.java:408)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
2024-03-01 16:27:05     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
2024-03-01 16:27:05     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
2024-03-01 16:27:05     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
2024-03-01 16:27:05     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
2024-03-01 16:27:05     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
2024-03-01 16:27:05     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
2024-03-01 16:27:05     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
2024-03-01 16:27:05     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
2024-03-01 16:27:05     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2024-03-01 16:27:05     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2024-03-01 16:27:05     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2024-03-01 16:27:05     at java.base/java.lang.Thread.run(Unknown Source)
2024-03-01 16:27:05 2024-03-01 10:57:05,743 ERROR p-thread-1 i.v.c.n.i.ConnectionBase   Broken pipe
```

**Comment by FrankMormino** [comment]
What was resolution that worked for resolving this issue?
