### ISSUE TITLE
"org.akhq.security.rule.AKHQSecurityRule.decompressGroups(io.micronaut.security.authentication.Authentication)" is null

### ISSUE THREAD

**Issue by karolcienkosz** [tchiotludo/akhq#1640]
After image update 0.24.0 --> dev  akhq returns error: 
`Internal Server Error: Cannot invoke "java.util.Map.values()" because the return value of "org.akhq.security.rule.AKHQSecurityRule.decompressGroups(io.micronaut.security.authentication.Authentication)" is null`
<img width="1905" alt="image" src="https://github.com/tchiotludo/akhq/assets/33066199/fe2bf4d7-1600-482a-8cfd-25f3fa44d66f">

```
2023-12-28 08:24:23,049 ERROR io-executor-thread-3 o.a.c.ErrorController Cannot invoke "java.util.Map.values()" because the return value of "org.akhq.security.rule.AKHQSecurityRule.decompressGroups(io.micronaut.security.authentication.Authentication)" is null
java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because the return value of "org.akhq.security.rule.AKHQSecurityRule.decompressGroups(io.micronaut.security.authentication.Authentication)" is null
	at org.akhq.controllers.AbstractController.getUserGroups(AbstractController.java:53)
	at org.akhq.controllers.AkhqController.getRights(AkhqController.java:225)
	at org.akhq.controllers.AkhqController.users(AkhqController.java:144)
	at org.akhq.controllers.$AkhqController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:442)
	at io.micronaut.context.DefaultBeanContext$BeanContextExecutionHandle.invoke(DefaultBeanContext.java:4282)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:223)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:74)
	at io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:480)
	at io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:457)
	at io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:196)
	at io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:196)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

I've found [PR1630](https://github.com/tchiotludo/akhq/pull/1630) and [ISSUE1616](https://github.com/tchiotludo/akhq/issues/1616) with information that roles/groups should be configured in different way.

In my scenario i used akhq instaled using helm and integrated with okta. Should I change my configuration(how?) or it is a bug and for now I cannot use dev image? 

Thanks in advance!

**Comment by AlexisSouquiere** [comment]
@karolcienkosz can you please paste your application.yml file ?
Did you took into account the breaking changes on roles/groups when upgrading to dev ?

**Comment by karolcienkosz** [comment]
@AlexisSouquiere  thx for example config. In my case it was cause by `default-group` for oidc. Using 0.24 it was enough to use `default-group: no-roles`
With dev I have to define group like
```
      oidc:
        enabled: true
        providers:
          okta:
            label: "Login with Okta"
            username-field: preferred_username
            default-group: akhq-default
            groups-field: groups
            groups:
              - name: "akhq-reader"
                groups
                  - reader
              - name: akhq-admin
                groups:
                  - admin
              - name: akhq-default
                groups:
                  - no-roles
```

**Comment by AlexisSouquiere** [comment]
Great, thanks for the update and for highlighting that I need to catch the NPE to show a better error message.
If everything is good for you you can close the isue !
