### ISSUE TITLE
Impossible to see the description of the topics when one of the brokers is down.

### ISSUE THREAD

**Issue by thedje** [tchiotludo/akhq#1684]
We are using version 0.24.0

When one of our brokers/zookeepers is down, we cannot see the description of our topics.

The error is:
```
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 15000ms
2024-03-13 13:03:50,651 WARN read-20332 org.akhq.log.access [Date: 2024-03-13T13:03:35.272308Z] [Duration: 15379 ms] [Url: GET /api/kafka- prod/group/topics] [Status: 500] [Ip: /10.128.4.1] [User: 72788B]
2024-03-13 13:03:51,671 WARN read-20336 o.a.k.c.NetworkClient [Consumer clientId=consumer-null-953, groupId=null] Bootstrap broker xxxx:29092 (id: -2 rack: null) disconnected
2024-03-13 13:03:51,704 ERROR read-20337 o.a.c.ErrorController Error for Describe Topics Offsets {}
java.lang.RuntimeException: Error for Describe Topics Offsets {}
at org.akhq.utils.Logger.call(Logger.java:31)
at org.akhq.modules.AbstractKafkaWrapper.describeTopicsOffsets(AbstractKafkaWrapper.java:129)
at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Exec.dispatch(Unknown Source)
at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
at org.akhq.modules.$KafkaWrapperRequestScope$Definition$Intercepted.describeTopicsOffsets(Unknown Source)
at org.akhq.repositories.TopicRepository.findByName(TopicRepository.java:108)
at org.akhq.controllers.NodeController.nodePartitions(NodeController.java:53)
at org.akhq.controllers.$NodeController$Definition$Exec.dispatch(Unknown Source)
at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
```
Is there a solution to overcome this problem?

**Comment by idoitu** [comment]
same here, as long as one server is down, it doesn't try to connect to the others instead.
