### ISSUE TITLE
Error navigating to consumer group from topic

### ISSUE THREAD

**Issue by shaneikennedy** [tchiotludo/akhq#1806]
```
react-dom.production.min.js:106 Uncaught TypeError: Cannot read properties of undefined (reading 'navigate')
    at onDetails (TopicGroups.jsx:135:31)
    at onClick (Table.jsx:379:30)
    at Object.Tx (react-dom.production.min.js:54:317)
    at Ax (react-dom.production.min.js:54:471)
    at Dx (react-dom.production.min.js:55:35)
    at Tv (react-dom.production.min.js:105:68)
    at Rb (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at Lg (react-dom.production.min.js:274:42)
    at rb (react-dom.production.min.js:52:375)
```
    
Repro:
- go to topic list
- choose topic with consumer group
- go to topic details
- consumer group tab
- see details of a consumer group

Result: no navigation to the consumer group detail page and console error above

**Comment by AlexisSouquiere** [comment]
Good catch, thanks !

**Comment by shaneikennedy** [comment]
You're fast @AlexisSouquiere !  We're testing and reporting as we find stuff, I try to contribute back as well 👍

**Comment by AlexisSouquiere** [comment]
We had this error several times during the move to React 18 🤯 But this one was missing !
Thanks a lot for reporting it !
