### ISSUE TITLE
ACLs screen fails to load if subjects contain unicode characters

### ISSUE THREAD

**Issue by richardtippl-ext90046** [tchiotludo/akhq#1920]
If the attached Kafka cluster has ACL configuration containing certificates with Unicode characters in the subject field, AKHQ completely fails to load the ACLs screen. This is because `btoa` used does not support non-latin characters.

see: https://developer.mozilla.org/en-US/docs/Web/API/Window/btoa#unicode_strings

AKHQ version: 0.25.1
```
Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at https://<domain>/ui/assets/index-BdxSfnGT.js:476:54779
    at Array.map (<anonymous>)
    at x5.handleData (https://<domain>/ui/assets/index-BdxSfnGT.js:476:54752)
    at x5.getAcls (https://<domain>/ui/assets/index-BdxSfnGT.js:476:54711)
```

**Comment by sonali131** [comment]
Hello sir can i contribute to your project?
