### ISSUE TITLE
Topic List and Consumer List seems to timeout

### ISSUE THREAD

**Issue by phills** [tchiotludo/akhq#203]
I use the KafkaHQ docker image and a Kafka service provider that isn't fast.  
Is there a timeout or memory configuration I can add?
Here is part of the log:

java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownServerException: The server experienced an unexpected error when processing the request.
at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
at org.kafkahq.modules.AbstractKafkaWrapper.lambda$describeConsumerGroups$16(AbstractKafkaWrapper.java:189)
at org.kafkahq.utils.Logger.call(Logger.java:19)
at org.kafkahq.modules.AbstractKafkaWrapper.**describeConsumerGroups**(AbstractKafkaWrapper.java:185)
...

**Comment by tchiotludo** [comment]
Really weird. 
This is not a timeout, the exception is more precise.
Seems to be a lost of connections or a network failure. 

Is this exception is always raise or some time? 
Do you have seen the KafkaHq interface ?

**Comment by phills** [comment]
Yes, precise. Only with consumer groups on the Consumers or Topics pages.  It occurs almost instantly.  The rest of KafkaHQ works very well!
I have about 200 consumers for 100 topics.

**Comment by tchiotludo** [comment]
You can remove the consumer group on the topic list with this configuration `kafkahq.topic.skip-consumer-groups`.
That will help this page, for the consumer group page, it will be conplicated, it need a big refactor on my side to speed up this page. Solution will come in few weeks / month (need to refactor the whole application) in order to handle cluster with some many groups

**Comment by tchiotludo** [comment]
But none to say that must be the broker that raise the error.
Don't you have an error on the broker side ?

**Comment by phills** [comment]
Thank you for your responsiveness.
My brokers run on a service provider.  I don't have access to the logs.  Sorry.
The error does occur more often when a few people are using the app or when there is load on broker.  That's why I'm thinking its a timeout or buffer size or stack size.  I did increase JVM memory with "-Xms512M -Xmx512M" and that made things a little better.

**Comment by tchiotludo** [comment]
closing due to inactivity
