### ISSUE TITLE
Kafka cluster on docker-compose fatal error 

### ISSUE THREAD

**Issue by clallavena** [tchiotludo/akhq#256]
I'm currently working on a new feature for akhq, according to that I try to test it with the docker-compose-dev.

The Kafka cluster lauching a fatal error and then exit:

```
kafka_1            | [2020-04-01 09:53:35,990] ERROR [KafkaServer id=1001] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka_1            | org.apache.kafka.common.KafkaException: Found directory /var/lib/kafka/data/data, 'data' is not in the form of topic-partition or topic-partition.uniqueId-delete (if marked for deletion).
kafka_1            | Kafka's log directories (and children) should only contain Kafka topic data.
kafka_1            | 	at kafka.log.Log$.exception$1(Log.scala:2611)
kafka_1            | 	at kafka.log.Log$.parseTopicPartitionName(Log.scala:2616)
kafka_1            | 	at kafka.log.LogManager.loadLog(LogManager.scala:268)
kafka_1            | 	at kafka.log.LogManager.$anonfun$loadLogs$12(LogManager.scala:353)
kafka_1            | 	at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:65)
kafka_1            | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
kafka_1            | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
kafka_1            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
kafka_1            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
kafka_1            | 	at java.lang.Thread.run(Thread.java:748)
kafka_1            | [2020-04-01 09:53:35,992] INFO [Log partition=__consumer_offsets-7, dir=/var/lib/kafka/data] Loading producer state till offset 0 with message format version 2 (kafka.log.Log)
kafka_1            | [2020-04-01 09:53:36,014] INFO [Log partition=__consumer_offsets-7, dir=/var/lib/kafka/data] Completed load of log with 1 segments, log start offset 0 and log end offset 0 in 25 ms (kafka.log.Log)
kafka_1            | [2020-04-01 09:53:36,014] INFO [KafkaServer id=1001] shutting down (kafka.server.KafkaServer)
```

I try to figure it out but i can't found out :thinking: 

If you have an idea on how to fix this I will include it to my PR 

Ty !

**Comment by tchiotludo** [comment]
Just try and no error on my side. 

Will need more information on this. 

Feel free to reopen with more details
