### ISSUE TITLE
Consumer-group tab in Topic is empty when setting skip-consumer-groups

### ISSUE THREAD

**Issue by RickardCardell** [tchiotludo/akhq#271]
Hi
First of all, thanks for an excellent job with this awesome tool!

We had issues with the GUI being slow on load when listing the topics so we tried out the setting 'skip-consumer-groups: true', which made a huge difference in startup and responsiveness. 

However, now when going to a specific topic, and then the Consumer Groups tab, it shows only 'No consumer group available ', even though there are consumer groups for the topic. ![Screenshot 2020-04-20 at 11 44 20](https://user-images.githubusercontent.com/101401/79753017-88bf1f00-8315-11ea-92f9-3c5f84d6aab1.png)

Feature or a bug?
I reckon a bug, since either the tab should be stating why it is empty or not show at all or preferably showing the consumer-groups attached to the topic.

Preferred behaviour: When having 'skip-consumer-groups: true', show the consumer-groups for the topic, even though it takes some time.

Release: 
0.12.0 snapshot 2e2cde3b851
0.14.0 snapshot acb9dcf8ff854cd5b4a6b44d010fe29432dc62ff

**Comment by tchiotludo** [comment]
Hey, 

It's a bug, the configuration create a var `skipConsumerGroups` that will block the fetch on every topic page (so the bug you have). 

Can you try (in 5 minutes) the dev image to see if it's works well ? 

Thanks for the report :+1:

**Comment by RickardCardell** [comment]
Hi
Thanks for the fix. I tried the dev-image with the fix and it looks like expected now  
//Rickard

**Comment by ankon** [comment]
While the request looks ok, it does mean that opening the topic page will now require to load consumer group data -- even when one doesn't actually look at that tab. In our case it actually brings akhq back to "unusable" (due to the amount of consumer groups we have). 

@RickardCardell would your use case still work if the consumer groups only get loaded when you click on that tab? @tchiotludo I could look into how to do that.

**Comment by RickardCardell** [comment]
> @RickardCardell would your use case still work if the consumer groups only get loaded when you click on that tab? @tchiotludo I could look into how to do that.
Yes, definitely. The performance penalty is expected when clicking on the consumer-groups tab.

**Comment by tchiotludo** [comment]
@ankon would be nice 👍

**Comment by tchiotludo** [comment]
@RickardCardell @ankon : I've made a fix on `dev` can you try please ?

**Comment by RickardCardell** [comment]
I've tried the fix. It worked well in a small environment, but in another I get a NullPointerException when I visit the consumer-group tab. The topics that I tried had at least one consumer-group.

 It's on a cluster with rather many topics and consumer-groups.

```
java.lang.NullPointerException
	at org.akhq.models.TopicPartition$ConsumerGroupOffset.<init>(TopicPartition.java:63)
	at org.akhq.models.ConsumerGroup.<init>(ConsumerGroup.java:69)
	at org.akhq.repositories.ConsumerGroupRepository.lambda$findByName$3(ConsumerGroupRepository.java:83)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.akhq.repositories.ConsumerGroupRepository.findByName(ConsumerGroupRepository.java:85)
	at org.akhq.repositories.ConsumerGroupRepository.findByTopic(ConsumerGroupRepository.java:90)
	at org.akhq.repositories.TopicRepository.findByName(TopicRepository.java:128)
	at org.akhq.repositories.TopicRepository.findByName(TopicRepository.java:105)
	at org.akhq.controllers.TopicController.render(TopicController.java:472)
	at org.akhq.controllers.TopicController.tab(TopicController.java:468)
	at org.akhq.controllers.$TopicControllerDefinition$$exec11.invokeInternal(Unknown Source)
```
Sorry that I can't provide more information than this at this point. I'll look into it further

**Comment by RickardCardell** [comment]
I suspect that consumer groups that have no topic assignment might cause the crash. The cluster has a few of those

**Comment by tchiotludo** [comment]
@RickardCardell, i tried to do a fix, but your cluster seems to be really strange :smile:

**Comment by RickardCardell** [comment]
@tchiotludo Indeed. If it works on that cluster, then it should work on most clusters ;)
Thanks for the fix. It seems to work and doesn't throw NPE:s anymore 👍
