### ISSUE TITLE
Authentication exception in 0.14.0 when having default-group with no roles 

### ISSUE THREAD

**Issue by RickardCardell** [tchiotludo/akhq#276]
Hello!
The pre-defined group `no-roles` doesn't work anymore after I've moved from 0.12 to 0.14. Also groups with no roles fails, so that might be a clue
I.e

```
  security:
    default-group: no-roles
    groups:
      readonly:
        roles:
          - topic/read
```

and

```
  security:
    default-group: foo
    groups:
      foo:
        roles: []
```

Exception when I run a docker on latest dev (commit 16c3a781e66732cbe0f93b5885bf7e6e942a296f):
```
io.micronaut.security.authentication.AuthorizationException
	at io.micronaut.security.filters.SecurityFilter.checkRules(SecurityFilter.java:179)
	at io.micronaut.security.filters.SecurityFilter.checkRules(SecurityFilter.java:218)
	at io.micronaut.security.filters.SecurityFilter.lambda$doFilterOnce$4(SecurityFilter.java:152)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FlowableSwitchIfEmpty.java:71)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:97)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onComplete(FlowableFlatMap.java:338)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:97)
	at io.reactivex.internal.operators.maybe.MaybeToFlowable$MaybeToFlowableSubscriber.onComplete(MaybeToFlowable.java:80)
	at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:96)
	at io.reactivex.internal.operators.maybe.MaybeDoOnEvent$DoOnEventMaybeObserver.onComplete(MaybeDoOnEvent.java:115)
	at io.micronaut.reactive.rxjava2.RxInstrumentedMaybeObserver.onComplete(RxInstrumentedMaybeObserver.java:96)
...
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:144)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Might be related to https://github.com/tchiotludo/akhq/issues/261 since the exception is similar

**Comment by tchiotludo** [comment]
It's related, there is a changed on micronaut part that I don't really understand for now. 
coming from this issue : https://github.com/micronaut-projects/micronaut-security/issues/6

maybe this one will fix it : #273

will look asap

**Comment by RickardCardell** [comment]
Thanks, no rush

I've tried the #273 fix, and that do redirects me to /login without an exception. However, now I can't authenticate so I can't test that the authentication really works

**Comment by RickardCardell** [comment]
Actually, Mr FatFingers here added extra double spaces in the ldap config, so that's why I couldn't login after applying the fix. Yaml is tricky sometimes.

Looks like the fix did it then :thumbsup:

**Comment by jorgheymans** [comment]
Seeing this as well, comment here https://github.com/tchiotludo/akhq/issues/261#issuecomment-617241499 is the easiest workaround if you don't want to rebuild.

**Comment by tchiotludo** [comment]
Hey there, I think the fix is in `dev`.
Can you try ?
