### ISSUE TITLE
groups without roles trigger NPE

### ISSUE THREAD

**Issue by jorgheymans** [tchiotludo/akhq#279]
This config construct triggers a NPE in `UserGroupUtils`. Basically what we're doing is define r/o access for everyone and filtering on the topic by regexp for each ldap group.

```
security:
 default-group: 
   - no-roles
 groups:
   abc:
     attributes:
       topics-filter-regexp: "abc.*"
 ldap:
   group:
     group-abc:
       name: "ABC_DEV"
       groups:
         - abc
         - reader
```

```
java.lang.NullPointerException: null
        at org.akhq.utils.UserGroupUtils.lambda$getUserRoles$1(UserGroupUtils.java:29)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.akhq.utils.UserGroupUtils.getUserRoles(UserGroupUtils.java:31)
        at org.akhq.modules.LdapContextAuthenticationMapper.map(LdapContextAuthenticationMapper.java:36)
```

**Comment by tchiotludo** [comment]
Hi, 
You don't provide any roles for your group that lead to this NPE: 

Change at least with that and I think it will work : 

```yaml
security:
 default-group: 
   - no-roles
 groups:
   abc:
     roles: []
     attributes:
       topics-filter-regexp: "abc.*"
 ldap:
   group:
     group-abc:
       name: "ABC_DEV"
       groups:
         - abc
         - reader
```

**Comment by jorgheymans** [comment]
Thanks for merging, for config clarity it may be better to indeed add the `roles: []` element but if you have many groups to manage it clutters a bit unnecessarily, hence my PR.

**Comment by tchiotludo** [comment]
understood ;) 
and still avoid a NPE thanks :+1:
