### ISSUE TITLE
Error for Describe Topic Config {} 

### ISSUE THREAD

**Issue by hanxuanliang** [tchiotludo/akhq#365]
```java
Internal Server Error: Error for Describe Topic Config {}
      java.lang.RuntimeException: Error for Describe Topic Config {}
        at org.akhq.utils.Logger.call(Logger.java:31)
        at org.akhq.modules.AbstractKafkaWrapper.describeConfigs(AbstractKafkaWrapper.java:290)
        at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$$exec13.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:60)
        at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$Intercepted.describeConfigs(Unknown Source)
        at org.akhq.repositories.ConfigRepository.find(ConfigRepository.java:48)
        at org.akhq.repositories.ConfigRepository.findByBrokers(ConfigRepository.java:27)
        at org.akhq.repositories.ConfigRepository.findByBroker(ConfigRepository.java:23)
        at org.akhq.controllers.NodeController.nodeConfig(NodeController.java:163)
        at org.akhq.controllers.NodeController.nodeConfigApi(NodeController.java:91)
        at org.akhq.controllers.$NodeControllerDefinition$$exec7.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2995)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:286)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$16(RoutingInBoundHandler.java:1474)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableSwitchMap.subscribeActual(FlowableSwitchMap.java:49)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FlowableSwitchIfEmpty.java:71)
        at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onComplete(RxInstrumentedSubscriber.java:97)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:426)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
```
Is it because the kafka version of the machine is too high? :hammer:

**Comment by tchiotludo** [comment]
seems really weird !! 
You have a standard open source kafka cluster with version 2.5 ? 
This api is very very old, I really don't see any reason that the method is not supported ! 

Maybe you can give me more insight about kafka cluster (local / kubernetes / aiven / confluent cloud) installation and akhq version ?

**Comment by hanxuanliang** [comment]
Sorry, case solved 💇 
The kafka version I connected to before was 0.x, but now it's 2.5, no problem.
Sorry again.

**Comment by tchiotludo** [comment]
Np 👍
