### ISSUE TITLE
basic auth not working

### ISSUE THREAD

**Issue by cloudcafetech** [tchiotludo/akhq#423]
Password generated as follows

```
[root@k3s kafka]# echo -n "password" | sha256sum
5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8  -
```

application.yml as follows,

```
akhq:
  connections:
    prod-cluster:
      properties:
        bootstrap.servers: prod-cluster-bootstrap-streaming.10.128.0.52.nip.io:443
        security.protocol: SSL
        ssl.truststore.password: mvBjjgcI4kKwyim0e7jCxAiZMjaxzTqG
        ssl.truststore.location: /data/super-user-prod-cluster-truststore.jks
        ssl.keystore.location: /data/super-user-prod-cluster-keystore.jks
        ssl.keystore.password: mvBjjgcI4kKwyim0e7jCxAiZMjaxzTqG
        ssl.key.password: kgaNT1PMIhKw
  # Auth & Roles (optional)
  security:
    default-group: reader # Default groups for all the user even unlogged user
    # Groups definition
    groups:
      - name: admin # Group name
        roles:  # roles for the group
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete
          - group/offsets/update
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
          - acls/read
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
      - name: topic-reader # Other group
        roles:
          - topic/read
    # Basic auth configuration
    basic-auth:
      - uasername: admin
        password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
        groups:
          - admin
```
Run docker 

```
docker run -d --name kadmin --restart=always -v /root/kafka/application.yml:/app/application.yml -v /root/kafka:/data -p 8081:8080 tchiotludo/akhq
```

logs from docker ..

```
[root@k3s kafka]# docker logs -f d7f67d8c2d00ef5d6f23a73c11778582f7786cd682755671de54d2e92a97ab2d
2020-09-29 17:27:43,354 INFO  main       i.m.c.e.DefaultEnvironment Established active environments: [gcp, cloud]
2020-09-29 17:27:46,474 INFO  main       i.m.runtime.Micronaut      Startup completed in 3290ms. Server Running: http://d7f67d8c2d00:8080
2020-09-29 17:27:58,059 INFO  pGroup-1-2 org.akhq.log.access        [Date: 2020-09-29T17:27:57.736622Z] [Duration: 317 ms] [Url: GET / 307] [Status: 0] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:27:58,528 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-09-29T17:27:58.412841Z] [Duration: 115 ms] [Url: GET /ui 200] [Status: 1135] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:27:59,021 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-09-29T17:27:58.94632Z] [Duration: 74 ms] [Url: GET /ui/static/css/2.7caccc14.chunk.css 304] [Status: -] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:27:59,034 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2020-09-29T17:27:58.951701Z] [Duration: 82 ms] [Url: GET /ui/static/css/main.9be09a44.chunk.css 304] [Status: -] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:27:59,280 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2020-09-29T17:27:59.250583Z] [Duration: 29 ms] [Url: GET /ui/static/js/2.8608a7d0.chunk.js 304] [Status: -] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:27:59,322 INFO  pGroup-1-2 org.akhq.log.access        [Date: 2020-09-29T17:27:59.28455Z] [Duration: 37 ms] [Url: GET /ui/static/js/main.9976c937.chunk.js 304] [Status: -] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:28:00,489 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2020-09-29T17:28:00.426773Z] [Duration: 62 ms] [Url: GET /ui/static/media/icon.648ce9c8.svg 304] [Status: -] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:28:00,491 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-09-29T17:28:00.384404Z] [Duration: 107 ms] [Url: GET /api/me 200] [Status: 16] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:28:00,917 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-09-29T17:28:00.873459Z] [Duration: 43 ms] [Url: GET /ui/static/media/logo.45903e1f.svg 304] [Status: -] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:28:00,919 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2020-09-29T17:28:00.882875Z] [Duration: 36 ms] [Url: GET /ui/static/media/fontawesome-webfont.af7ae505.woff2 304] [Status: -] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:28:10,002 INFO  pGroup-1-2 org.akhq.log.access        [Date: 2020-09-29T17:28:09.689827Z] [Duration: 312 ms] [Url: POST /login 303] [Status: 0] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:28:10,410 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-09-29T17:28:10.404549Z] [Duration: 5 ms] [Url: GET /api/me 200] [Status: 16] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:28:40,895 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2020-09-29T17:28:40.889259Z] [Duration: 6 ms] [Url: POST /login 303] [Status: 0] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:28:41,636 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2020-09-29T17:28:41.629863Z] [Duration: 5 ms] [Url: GET /api/me 200] [Status: 16] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:32:40,039 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2020-09-29T17:32:40.030921Z] [Duration: 8 ms] [Url: POST /login 303] [Status: 0] [Ip: 42.110.142.30] [Length: 8080] [Port: {}]
2020-09-29 17:32:40,669 INFO  pGroup-1-2 org.akhq.log.access        [Date
```

**but not able to login, rotating wheel and stop.**

**Comment by tchiotludo** [comment]
Hi,
`uasername` is wrong 😃

**Comment by cloudcafetech** [comment]
why ? I can use **admin** as u username ?

or any predefined user is there?

**Comment by cloudcafetech** [comment]
Ah! I modified 

```
    # Basic auth configuration
    basic-auth:
      - username: admin
        password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
        groups:
          - admin
```

but again same issue ... :(

**Comment by tchiotludo** [comment]
ok understood !! 

The configuration files have changed on `dev` ! 
Here is the configuration files for last release : 

https://github.com/tchiotludo/akhq/blob/ec99a219126220e4f85ade6c56008fcb62e984f8/application.example.yml#L156-L162

**Comment by cloudcafetech** [comment]
I changed 

```
    # Basic auth configuration
    basic-auth:
      user: admin
        password: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
        groups:
          - admin
```

now container keep on restarting

```
[root@k3s kafka]# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                         PORTS               NAMES
f3c8c53d0e2c        tchiotludo/akhq     "docker-entrypoint.s…"   40 seconds ago      Restarting (1) 6 seconds ago                       kadmin
[root@k3s kafka]# docker logs -f f3c8c53d0e2c
2020-09-30 09:23:13,615 INFO  main       i.m.c.e.DefaultEnvironment Established active environments: [gcp, cloud]
2020-09-30 09:23:13,957 ERROR main       i.m.runtime.Micronaut      Error starting Micronaut server: mapping values are not allowed here
 in 'reader', line 48, column 17:
            password: 5e884898da28047151d0e56f8dc629 ...
                    ^

org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'reader', line 48, column 17:
            password: 5e884898da28047151d0e56f8dc629 ...
                    ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:869)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)

```

**Comment by tchiotludo** [comment]
clearly the error is telling you that your yaml is invalid, make a try here : http://www.yamllint.com/

**Comment by nitikas99** [comment]
Message: Error resolving property value [akhq.security.groups]. Unable to convert value [[{name=admin, roles=[topic/read, topic/insert, topic/delete, topic/config/update, node/read, node/config/update, topic/data/read, topic/data/insert, topic/data/delete, group/read, group/delete, group/offsets/update, registry/read, registry/insert, registry/update, registry/delete, registry/version/delete, acls/read, connect/read, connect/insert, connect/update, connect/delete, connect/state/update]}, {name=topic-reader, roles=[topic/read]}]] to target type [Map<String, Group>] due to: Cannot convert an iterable with more than 1 value to a non collection object
Path Taken: new JwtSecurityWarning() --> JwtSecurityWarning.securityProperties --> SecurityProperties.setGroups([Map groups])
Path Taken: new JwtSecurityWarning() --> JwtSecurityWarning.securityProperties --> SecurityProperties.setGroups([Map groups])
	at io.micronaut.context.exceptions.DependencyInjectionException.missingProperty(DependencyInjectionException.java:289)
	at io.micronaut.context.AbstractInitializableBeanDefinition.lambda$resolvePropertyValue$10(AbstractInitializableBeanDefinition.java:2043)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolvePropertyValue(AbstractInitializableBeanDefinition.java:2043)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getPropertyValueForSetter(AbstractInitializableBeanDefinition.java:1086)
	at org.akhq.configs.$SecurityProperties$Definition.injectBean(Unknown Source)
	at org.akhq.configs.$SecurityProperties$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2879)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2800)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2065)
	at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForField(AbstractInitializableBeanDefinition.java:1603)
	at org.akhq.configs.$JwtSecurityWarning$Definition.injectBean(Unknown Source)
	at org.akhq.configs.$JwtSecurityWarning$Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2354)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2305)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2746)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915)
	... 9 common frames omitted
	I am getting this error with above configuration
