### ISSUE TITLE
Out of Memory issue

### ISSUE THREAD

**Issue by vikesh-chauhan** [tchiotludo/akhq#481]
I am deploying AKHQ on a container with 6gb memory and 2 core processor and receiving the following exception on the pod when loading AKHQ

```
Exception in thread "pool-1-thread-3" java.lang.OutOfMemoryError: Java heap space
	at com.fasterxml.jackson.core.util.ByteArrayBuilder.toByteArray(ByteArrayBuilder.java:156)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3434)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:212)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:221)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeBodyAsByteBuf(RoutingInBoundHandler.java:1419)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeBodyWithCodec(RoutingInBoundHandler.java:1365)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$subscribeToResponsePublisher$12(RoutingInBoundHandler.java:1293)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$$Lambda$644/0x00000001007fcc40.apply(Unknown Source)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.drain(FlowableSwitchMap.java:307)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapInnerSubscriber.onSubscribe(FlowableSwitchMap.java:366)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onSubscribe(RxInstrumentedSubscriber.java:54)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:58)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.onNext(FlowableSwitchMap.java:129)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.micronaut.http.context.ServerRequestTracingPublisher$1.lambda$onNext$1(ServerRequestTracingPublisher.java:60)
	at io.micronaut.http.context.ServerRequestTracingPublisher$1$$Lambda$674/0x0000000100817040.run(Unknown Source)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
	at io.micronaut.http.context.ServerRequestTracingPublisher$1.onNext(ServerRequestTracingPublisher.java:60)
	at io.micronaut.http.context.ServerRequestTracingPublisher$1.onNext(ServerRequestTracingPublisher.java:52)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:68)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onNext(RxInstrumentedSubscriber.java:68)
	at io.reactivex.internal.operators.flowable.FlowableSwitchMap$SwitchMapSubscriber.drain(FlowableSwitchMap.java:307)
```
I have disabled metrics as well
```
    akhq:
      micronaut:
        jmx:
          add-to-factory: false
          register-endpoints: false
        metrics:
        enabled: false
```

Can you help identify what could be the issue or how much memory would the app need. Thanks!

**Comment by tchiotludo** [comment]
Can you know which api endpoint is causing this exception ?
Can you also try with dev image please ? I fix an issue with an endpoint that can lead to a recursive object and send a lot of data on consumer group page.

**Comment by sverrehu** [comment]
Whenever I get unexpected OOM from anything Kafka-related, I check for misconfiguration resulting in mixture of plaintext and SSL, for instance a client expecting plaintext, and connecting to a broker configured with SSL.

https://issues.apache.org/jira/browse/KAFKA-4090

**Comment by vikesh-chauhan** [comment]
@tchiotludo I would not be able to use the dev image since i am using the helm chart. I am currently using chart version 0.1.3. Is there a way i can test new versions using helm chart?

**Comment by vikesh-chauhan** [comment]
Also this exception is caused by i am trying to get a list of all topics.

**Comment by tchiotludo** [comment]
You can change the image : https://github.com/tchiotludo/akhq/blob/dev/helm/akhq/values.yaml#L5
Just put dev and you will go to dev image. 

Can you send me [debug](https://github.com/tchiotludo/akhq#debugging-akhq-performance-issues) information from log please ? 

When you said trying to get a list of all topics, are you chaging the default pagination ?

**Comment by vikesh-chauhan** [comment]
@tchiotludo I tried overriding the tag but i think since i am downloading helm chart as dependent chart with version 0.1.3, the dev image is not the latest. I am getting the following message when i use the dev tag with version 0.1.3
```
2020-10-29 21:44:16,837 WARN  1-thread-2 org.akhq.log.access        [Date: 2020-10-29T21:44:16.837481Z] [Duration: 0 ms] [Url: GET /api/me] [Status: 500] [Ip: /10.1.1.115] [User: -]
2020-10-29 21:45:04,189 WARN  1-thread-2 org.akhq.log.access        [Date: 2020-10-29T21:45:04.188602Z] [Duration: 0 ms] [Url: GET /] [Status: 500] [Ip: /10.1.0.227] [User: -]
```
My requirement.yaml file looks like this
```
dependencies:
  - name: akhq
    version: 0.1.3
    repository: "@akhq"
    alias: kafka-akhq
    tags:
      - kafka-akhq
```
Overriden configuration in values.yaml file
```
kafka-akhq:
  image:
    tag: dev
  configuration: |
    akhq:
      micronaut:
        jmx:
          add-to-factory: false
          register-endpoints: false
        metrics:
        enabled: false
```

**Comment by tchiotludo** [comment]
You only this configuration in your yaml ? 
Where is the cluster configuration etc ... ? 

What is displayed on the webpage that lead to the 500 error ?

**Comment by vikesh-chauhan** [comment]
I am downloading the AKHQ helm chart in my requirements.yaml code. The helm chart version is 0.1.3. I am deploying the helm chart in AWS EKS cluster (this configuration is separate). 

The webpage is blank screen leading to 500 error. It times out after sometime. Will helm chart 0.1.3 have latest changes from dev? or will that chart support dev tag?

Below is my akhq configuration

kafka-akhq:
  image:
    tag: dev
  configuration: |
    akhq:
      micronaut:
        jmx:
          add-to-factory: false
          register-endpoints: false
        metrics:
        enabled: false
  security:
    akhq:
      connections:
        ods-messaging:
          properties:
            bootstrap.servers:<bootstrap URL>
            security.protocol: SSL
            ssl.truststore.location: /usr/local/openjdk-11/lib/security/cacerts
            ssl.truststore.password: changeit
          schema-registry:
            url: <schema registry URL>           
      security:
        basic-auth:
          user: admin
          password: <password>
          groups:
            - admin
        groups:
          admin:
            roles:
              - topic/read
              - topic/insert
              - topic/delete
              - topic/config/update
              - node/read
              - node/config/update
              - topic/data/read
              - topic/data/insert
              - topic/data/delete
              - group/read
              - group/delete
              - group/offsets/update
              - registry/read
              - registry/insert
              - registry/update
              - registry/delete
              - registry/version/delete
              - acls/read
              - connect/read
              - connect/insert
              - connect/update
              - connect/delete
              - connect/state/update

**Comment by tchiotludo** [comment]
Yes the chart support dev image, I don't see the issue here. 
Maybe a port-forward to the pod to avoid the ingress, and have a really output for the 500 errors. 
Without this error, I'm completely blindness and cannot help ...

**Comment by tchiotludo** [comment]
closing due to inactivity, fell free to reopen
