### ISSUE TITLE
NettyHttpServer Unable to start server. Additional specified server port 8081 already in use

### ISSUE THREAD

**Issue by klDen** [tchiotludo/akhq#569]
Hi,

Would it be possible to modify Netty port?

It seems like NettyHttpServer is trying to listen on port 8081 while Micronaut listens on 8080.

```
Jan 25 14:23:46 java[19406]: 2021-01-25 14:23:46,703 ERROR main       i.m.h.s.n.NettyHttpServer  Unable to start server. Additional specified server port 8081 already in use.
Jan 25 14:23:46 java[19406]: 2021-01-25 14:23:46,706 ERROR main       i.m.runtime.Micronaut      Error starting Micronaut server: Unable to start Micronaut server on port: 8080
Jan 25 14:23:46 java[19406]: io.micronaut.http.server.exceptions.ServerStartupException: Unable to start Micronaut server on port: 8080
Jan 25 14:23:46 java[19406]:         at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:337)
Jan 25 14:23:46 java[19406]:         at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:110)
Jan 25 14:23:46 java[19406]:         at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:70)
Jan 25 14:23:46 java[19406]:         at java.base/java.util.Optional.ifPresent(Optional.java:183)
Jan 25 14:23:46 java[19406]:         at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
Jan 25 14:23:46 java[19406]:         at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
Jan 25 14:23:46 java[19406]:         at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
Jan 25 14:23:46 java[19406]:         at org.akhq.App.main(App.java:27)

```

**Comment by klDen** [comment]
I found out that the endpoint has been changed to port 8081 according to commit https://github.com/tchiotludo/akhq/commit/477c7046790e1b8371ca73da37df82c375e360bb .

**Comment by tchiotludo** [comment]
Good catch 👍
