### ISSUE TITLE
Cannot change default monitoring endpoint port

### ISSUE THREAD

**Issue by andritch** [tchiotludo/akhq#633]
The readme states

> Several monitoring endpoint is enabled by default and available on port 8081 only.
You can disable it, change the port or restrict access only for authenticated users following micronaut configuration below.

However, when I change the appropriate config in my application.yml to below (based on https://docs.micronaut.io/2.1.3/guide/index.html#providedEndpoints)
```
server:
    port: 9090 # App server port
  endpoints:
    all:
      port: 9091 # Additional endpoints port
akhq:
  server:
....
```

I'm running docker on linux using

`docker run -d --net=host --name=akhq --restart unless-stopped -v /app/application.yml:/app/application.yml tchiotludo/akhq:0.17.0`

It conflicts with another app on 8081. Notice despite the config to port 9091 above, it still prints 8081 in the error below

```
2021-03-12 17:02:08,735 INFO  main       i.m.c.e.DefaultEnvironment Established active environments: [ec2, cloud]
2021-03-12 17:02:11,608 ERROR main       i.m.h.s.n.NettyHttpServer  Unable to start server. Additional specified server port 8081 already in use.
2021-03-12 17:02:11,613 ERROR main       i.m.runtime.Micronaut      Error starting Micronaut server: Unable to start Micronaut server on port: 9090
io.micronaut.http.server.exceptions.ServerStartupException: Unable to start Micronaut server on port: 9090
        at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:337)
        at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:110)
        at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:70)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:68)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
        at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
        at org.akhq.App.main(App.java:27)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Unknown Source)
        at java.base/sun.nio.ch.Net.bind(Unknown Source)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134)
```

**Comment by tchiotludo** [comment]
Just changed with that : 
```yaml
micronaut: 
  server:
    port: 9090 # App server port
endpoints:
  all:
    port: 9091 # Additional endpoints port
akhq:
  server:
....
And it will be working :smiley:

**Comment by andritch** [comment]
That worked! Ugh...I hate Yaml... 😄 

Thanks!
