### ISSUE TITLE
Error "JSONArray cannot be cast to class java.lang.String" when using a List of Regexp to filter topic available for group

### ISSUE THREAD

**Issue by apellegr06** [tchiotludo/akhq#669]
Hello,

I have just deployed the last dev version in order to try the new functionnality "List of Regexp to filter topic available for group".

Before modifying the topics-filter-regexp it was working :

```
    groups:
      test:
        name: test
        roles:
          - topic/read
          - group/read
          - topic/data/read
          - topic/data/insert
          - group/offsets/update
        attributes:
          topics-filter-regexp: ".*"
```

And after I obtain the joined error when I connect on my cluster and try to list the topic :

```
    groups:
      test:
        name: test
        roles:
          - topic/read
          - group/read
          - topic/data/read
          - topic/data/insert
          - group/offsets/update
        attributes:
          topics-filter-regexp:
            - ".*"
```

The error :

```
Internal Server Error: class com.nimbusds.jose.shaded.json.JSONArray cannot be cast to class java.lang.String (com.nimbusds.jose.shaded.json.JSONArray is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class com.nimbusds.jose.shaded.json.JSONArray cannot be cast to class java.lang.String (com.nimbusds.jose.shaded.json.JSONArray is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at org.akhq.repositories.AbstractRepository.isMatchRegex(AbstractRepository.java:27)
	at org.akhq.repositories.TopicRepository.findByName(TopicRepository.java:94)
	at org.akhq.controllers.TopicController.partitions(TopicController.java:212)
	at org.akhq.controllers.$TopicControllerDefinition$$exec8.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:474)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1363)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:148)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by tchiotludo** [comment]
@twobeeb : what do you think about that ?

**Comment by twobeeb** [comment]
You must have forgot to force pull the latest "dev".

Here's the behavior I have on a AKHQ instance I justed poped for this issue "tchiotludo/akhq:dev" : 
````yaml
  security:
    default-group: reader
    groups:
      reader:
        roles:  
          - topic/read
        attributes:
          topics-filter-regexp:
            - "FDW-.*"

````

![image](https://user-images.githubusercontent.com/6431261/114398619-4a62e580-9ba0-11eb-8b9a-1e65b940d21b.png)

If I set the filter like you did : 
````yaml
  security:
    default-group: reader
    groups:
      reader:
        roles:  
          - topic/read
        attributes:
          topics-filter-regexp:
            - ".*"
````
![image](https://user-images.githubusercontent.com/6431261/114398913-a4fc4180-9ba0-11eb-8ac7-177eaab12d7c.png)

**Comment by apellegr06** [comment]
Here is what I done to pull the branch :

 docker pull tchiotludo/akhq:dev

It's not that ?

**Comment by twobeeb** [comment]
Try removing the existing docker image first ``docker rmi tchiotludo/akhq:dev``

**Comment by tchiotludo** [comment]
I've just can't reproduced on my side. 
Maybe your jwt token is broken ?
Try with private navigation please

**Comment by apellegr06** [comment]
The same behaviour in private, and also with others navigator like Edge ou opera.

And here is my complete configuration file :

```
micronaut:
  session:
    http:
      cookie-max-age: 1d
  ssl:
    enabled: true
    port: 8082
    key-store:
      path: file:xxxxxxxxxxxxxx
# ---- [ ADD KEYSTORE PASSWORD AFTER THIS LINE ] ----
      password: xxxxxx
      type: JKS
  security:
    enabled: true
    ldap:
      default:
        context:
          server: 'xxxxxxxxxxxxx'
          managerDn: 'xxxxxxxxxxxxx'
          managerPassword: 'xxxxxx'
        search:
          base: 'xxxxxxxxxxxxxxx'
        groups:
          enabled: true
          base: 'xxxxxxxxxxxx'

akhq:
  server:
    base-path: "" # if behind a reverse proxy, path to kafkahq without trailing slash (optional). Example: kafkahq is
                  # behind a reverse proxy with url http://my-server/kafkahq, set base-path: "/kafkahq".
                  # Not needed if you're behind a reverse proxy with subdomain http://kafkahq.my-server/
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]" # Logger format

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed
        default.api.timeout.ms: 60000

  # list of kafka cluster available for kafkahq
  connections:
# ---- [ ADD CLUSTER CONNECTION AFTER THIS LINE ] ----
    CLUSTER1:
      properties:
        bootstrap.servers: "xxxxxxxxxxxxxxx"
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: xxxxxxxxxxxxxxxxx
        principal="xxxxxxxxxxxx";


  pagination:
    page-size: 25 # number of elements per page (default : 25)
    threads: 16 # Number of parallel threads to resolve page

  # Topic list display options (optional)
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"

  # Topic display data options (optional)
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 50 # max record per page (default: 50)
    poll-timeout: 1000 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.

  # Auth & Roles (optional)
  security:
    default-group: no-roles

    # Groups definition
    groups:
      test:
        name: test
        roles:
          - topic/read
          - group/read
          - topic/data/read
          - topic/data/insert
          - group/offsets/update
        attributes:
          topics-filter-regexp:
            - "topic1"
            - "topic2"

    # Ldap Groups configuration (when using ldap)
    ldap:
      groups:
        - name: test
          groups:
            - test

```

**Comment by apellegr06** [comment]
And for information, I use jdk-11.0_5

**Comment by tchiotludo** [comment]
Are you sur your are using the good jar ? 
If you build by yourself, please make a test with official `dev` docker image please.
Supporting custom build jar is impossible for us

**Comment by apellegr06** [comment]
I think yes, I do that :

docker pull tchiotludo/akhq:dev
docker create --name cont1 tchiotludo/akhq:dev
docker cp cont1:/app/akhq.jar .

**Comment by tchiotludo** [comment]
I can't reproduce, please provide a docker-compose file like this [one](https://github.com/tchiotludo/akhq/blob/dev/docker-compose.yml) with the bug please

**Comment by apellegr06** [comment]
I am not using docker to run akhq, just to get the obtain the akhq.jar

Here is the identifier of the image :

Digest: sha256:9d948c46798be94a9b53e25d539563d21915b3b1de18202e2e8635782eaa1cf2

**Comment by tchiotludo** [comment]
No matter how you have akhq, we just need a reproduction method. 
So docker-compose (with full configuration) is the only option I think to reproduce the issue. 
If you don't provide this, we can't help, since we can't reproduce the issue

**Comment by apellegr06** [comment]
My Bad ! I was using the wrong jar name in my script, still on the kafkahq.jar and not akhq.jar, so an old one.
Thank you, and so sorry for the loose of time
