### ISSUE TITLE
Error while accessing topic without a schema

### ISSUE THREAD

**Issue by AntAreS24** [tchiotludo/akhq#670]
I'm using AKHQ 0.17.0 and I've just integrated it with TIBCO Schema Repository and it's working fine for the topics with a schema, but it's failing with the following error on topics without schema.

Not all topic in my organisation will use a schema. It's up to the project to decide. Some project will also using JSON message within Kafka.

```
Internal Server Error: Error for Consume with options {}
java.lang.RuntimeException: Error for Consume with options {}
	at org.akhq.utils.Debug.call(Debug.java:75)
	at org.akhq.repositories.RecordRepository.consume(RecordRepository.java:103)
	at org.akhq.controllers.TopicController.data(TopicController.java:187)
	at org.akhq.controllers.$TopicControllerDefinition$$exec5.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:474)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1363)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:148)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at com.tibco.messaging.schema.registry.SchemaRegistryCache.createRegistryService(SchemaRegistryCache.java:83)
	at com.tibco.messaging.schema.registry.SchemaRegistryCache.<init>(SchemaRegistryCache.java:69)
	at com.tibco.messaging.kafka.avro.AvroSerDe.configure(AvroSerDe.java:101)
	at com.tibco.messaging.kafka.avro.AvroSerDe.configure(AvroSerDe.java:109)
	at org.akhq.repositories.SchemaRegistryRepository.getKafkaAvroDeserializer(SchemaRegistryRepository.java:242)
	at org.akhq.repositories.RecordRepository.newRecord(RecordRepository.java:433)
	at org.akhq.repositories.RecordRepository.lambda$consumeNewest$14(RecordRepository.java:295)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2191)
	at java.base/java.util.stream.Nodes$CollectorTask$OfRef.doLeaf(Nodes.java:2201)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.Nodes.collect(Nodes.java:336)
	at java.base/java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:109)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.base/java.util.stream.SortedOps$OfRef.opEvaluateParallel(SortedOps.java:157)
	at java.base/java.util.stream.AbstractPipeline.opEvaluateParallelLazy(AbstractPipeline.java:710)
	at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(AbstractPipeline.java:434)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.akhq.repositories.RecordRepository.consumeNewest(RecordRepository.java:311)
	at org.akhq.repositories.RecordRepository.lambda$consume$4(RecordRepository.java:109)
	at org.akhq.utils.Debug.call(Debug.java:68)
	... 20 more
```

Could you please confirm if this is a TIBCO error (looking at the stacktrace it looks like it) or is it something AKHQ can prevent?

Ben

**Comment by tchiotludo** [comment]
hard to say, the last starting stacktrace part related to akhq is only the declaration of the schema registry client.
Like that, I have the felling that it's should not failed (we are only trying to init a client) but since source code of the tibco part is closed I can't be sure... 
Maybe @ebowden-tibco could help since he was the one that implement the feature ?

**Comment by ebowden-tibco** [comment]
@AntAreS24 could you share the schema registry part of your config file? That particular NPE could happen if you've configured a secure (https) schema repo URL but haven't set the ``ftl.trust.type`` property (you should be able to set this under the 'properties' list in your ``schema-registry`` config block).  You can try setting ``ftl.trust.type`` to ``"everyone"`` and see if the error goes away (don't use ``"everyone"`` in production, however, as it's not secure).  I'm not sure how the same config would work with some topics but not with others, however.  If it's failing on registry client creation, it should fail the same way regardless of what messages are in a topic.

**Comment by AntAreS24** [comment]
Let me try with the recommendation above and I'll report back.

**Comment by AntAreS24** [comment]
@ebowden-tibco, Just to clarify few things:
1) I can see/browse the schemas 
2) You are correct. Both topics with or without schema are failing with the same error.
3) Same error with the set to `ftl.trust.type: everyone`

I just had a chat with Mihai from TIBCO support and we noticed the code doesn't take any extra parameter from the `schema-registry.properties` section, but it does from the `<cluster>.properties`.

So I've changed the config to this and it's not throwing errors anymore, but I need to know how to fix that without using Everyone.

```
akhq
  connections:
    kafka-dev-cluster:
      properties:
        bootstrap.servers: "server1:9082,server1:9083,server1:9084"
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="<password";
        ssl.truststore.location: /opt/certs/truststore.jks
        ssl.truststore.password:
        ftl.trust.type: "everyone" # < --- working here.
      schema-registry:
        url: "https://server1:13134/schema/v1" # schema registry url (optional)
        type: "tibco" # schema registry type (optional). Supported types are "confluent" (default) or "tibco"
        # Basic Auth user / pass
        basic-auth-username: schema_writer
        basic-auth-password: <password>
        properties: # standard kafka properties (optional)
          ssl.protocol: TLS
          ssl.truststore.location: /opt/certs/truststore.jks
          ssl.truststore.password:
          ftl.trust.type: "everyone" # < --- NOT working here.
```

**Comment by mmaties-tibco** [comment]
If ftl.trust.type is missing then use -Djavax.net.ssl.trustStore, if set ... a bit more secure than "everyone". 

Enhancement candidate,  @ebowden-tibco  ? 

(also - props to Ludo for  config.putAll(this.kafkaModule.getConnection(clusterId).getProperties())  from org.akhq.repositories.SchemaRegistryRepository) 

Thanks!

**Comment by tchiotludo** [comment]
@ebowden-tibco @mmaties-tibco I'm completely blindness on this part since it need proprietary software, I let you make the modification needed on a new PR
