### ISSUE TITLE
java.lang.RuntimeException: Error for Describe Topics Offsets {}

### ISSUE THREAD

**Issue by tibco-derek** [tchiotludo/akhq#684]
Hi,

In order to simulate one-broker failure situation, I killed one broker in a 3-broker cluster. With AKHQ 0.17, I found that when I click the "topics" on the left, the GUI has the following error. How could we let the AKHQ GUI keep working under this situation?  

This issue only happens when a broker with a topic with replication factor=1, goes down, then AKHQ topic GUI will have the errors below. Restarting AKHQ jar file won't help as I think the GUI needs to get all topic info provided by ZK.

I do hope this can be fixed. For a cluster of 3 brokers, if a broker with 1-RF topic goes down, that would lead to the failure of AKHQ Topic GUI even though the remaining 2 brokers are running. 1-RF topic may be accidentally configured by AKHQ beginners.
 
Thanks,
Derek

2021-04-23 14:57:33,879 ERROR pGroup-1-8 o.a.c.ErrorController      Error for Describe Topics Offsets {}
java.lang.RuntimeException: Error for Describe Topics Offsets {}
	at org.akhq.utils.Logger.call(Logger.java:31)
	at org.akhq.modules.AbstractKafkaWrapper.describeTopicsOffsets(AbstractKafkaWrapper.java:122)
	at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$$exec6.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:73)
	at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$Intercepted.describeTopicsOffsets(Unknown Source)
	at org.akhq.repositories.TopicRepository.findByName(TopicRepository.java:105)
	at org.akhq.repositories.TopicRepository.lambda$list$0(TopicRepository.java:59)
	at org.akhq.utils.PagedList.of(PagedList.java:70)
	at org.akhq.repositories.TopicRepository.list(TopicRepository.java:59)
	at org.akhq.controllers.TopicController.list(TopicController.java:80)
	at org.akhq.controllers.$TopicControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:474)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1363)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:148)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 15002ms

**Comment by tchiotludo** [comment]
I know, the same issue than this old one :cry:  https://github.com/tchiotludo/akhq/issues/137 
For now, AKHQ is not resilient for this issue ... 
We need to catch this, but this is a bug refactor I think.
We need here : https://github.com/tchiotludo/akhq/blob/f691db000f675d1987046fac14c0408725ec93c5/src/main/java/org/akhq/repositories/TopicRepository.java#L104-L124
To remove this 2 call and make this one async on the react part :  
```java
        Map<String, List<Partition.Offsets>> topicOffsets = kafkaWrapper.describeTopicsOffsets(clusterId, filteredTopics);
        topicOffsets.get(description.getValue().name()),
```
Closing since there already an issue about that
