### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by blezoray** [tchiotludo/akhq#758]
Hello,

First, thanks for the job on AKHQ !

In order to be compliant with different kafka cluster configuration, I configured in a Openshift template, 3 connections in my application.yml:
```yaml
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name

  # default kafka properties for each clients, available for admin / producer / consumer (optional)
  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed

  # list of kafka cluster available for akhq
  connections:
    # Cluster without authentication
    my-cluster:
      properties:
        bootstrap.servers: "my-cluster-kafka-bootstrap.blz.svc.cluster.local:9092"

    # Cluster with SCRAM-SHA-512 authentication over TLS
    my-cluster-sasl-tls:
      properties:
        bootstrap.servers: "my-cluster-kafka-bootstrap.blz.svc.cluster.local:9093"
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="adminuser" password="xmEjVkTqs5d7";
        # Path of the truststore (that will contains the authority that are created the server certificate)
        ssl.truststore.location: /app/cluster-ca-certs/ca.p12
        # Password of the truststore
        ssl.truststore.password: DrHtiILESHgO
        # Type of the keystore (PKCS12 or JKS)
        ssl.truststore.type: PKCS12

    # Cluster with TLS authentication
    my-cluster-tls:
      properties:
        bootstrap.servers: "my-cluster-kafka-bootstrap.blz.svc.cluster.local:9093"
        security.protocol: SSL
        # Path of the truststore (that will contains the authority that are created the server certificate)
        ssl.truststore.location: /app/cluster-ca-certs/ca.p12
        # Password of the truststore
        ssl.truststore.password: DrHtiILESHgO
        # Type of the keystore (PKCS12 or JKS)
        ssl.truststore.type: PKCS12
        #
        # Path of the keystore (that will contains the authority that are created the server certificate)
        ssl.keystore.location: /app/user-cert/user.p12
        # Password of the keystore
        ssl.keystore.password: kHDlGiVADpdb
        # Type of the keystore (PKCS12 or JKS)
        ssl.keystore.type: PKCS12
```

But, if I opened AKHQ to a cluster configuration that doesn't match the TLS configuration, AKHQ generates in loop this message (14 millions per day !):
```log
2021-07-13 08:33:46,151 [31mWARN [0;39m [35minclient-3[0;39m [36mc.a.i.AdminMetadataManager[0;39m [AdminClient clientId=adminclient-3] Metadata update failed due to authentication error
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLProtocolException: Unexpected handshake message: server_hello
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:430)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:514)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:291)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1333)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1264)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Is there a way to configure AKHQ to limit/stop logging this error ?

Rgds.

**Comment by tchiotludo** [comment]
You can remove the error with micronaut configuration for logger :
```yaml
logger:
  levels:
   org.apache.kafka.common.errors.SslAuthenticationException: ERROR
```

**Comment by blezoray** [comment]
I added this but I have the same behavior:
```yaml
micronaut:
  logger:
    levels:
      # Disable SSL handshake failed error logs
      org.apache.kafka.common.errors.SslAuthenticationException: ERROR
akhq:
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
```

**Comment by blezoray** [comment]
With this configuration:
```yaml
logger:
  levels:
    # Disable SSL handshake failed error logs
    org.apache.kafka.common.errors.SslAuthenticationException: ERROR
akhq:
...
```
The parameter seems to be taken into account :
```
2021-07-13 11:41:34,718 INFO  main       i.m.c.e.DefaultEnvironment Established active environments: [k8s, cloud, secrets]
2021-07-13 11:41:42,110 INFO  main       iesLoggingLevelsConfigurer Setting log level 'ERROR' for logger: 'org.apache.kafka.common.errors.ssl-authentication-exception'
2021-07-13 11:41:42,110 INFO  main       iesLoggingLevelsConfigurer Setting log level 'ERROR' for logger: 'org.apache.kafka.common.errors.SslAuthenticationException'
2021-07-13 11:41:47,410 INFO  main       i.m.runtime.Micronaut      Startup completed in 13398ms. Server Running: http://akhq-6b7745c8f7-6cpmg:8080
```
But it continues to log SSL handshake errors...
```
2021-07-13 11:44:41,708 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-07-13T11:44:41.708311Z] [Duration: 0 ms] [Url: GET /ui] [Status: 200] [Ip: /10.130.18.1] [User: -]
2021-07-13 11:44:42,608 WARN  inclient-1 o.a.k.c.NetworkClient      [AdminClient clientId=adminclient-1] Connection to node -1 (my-cluster-kafka-bootstrap.blz.svc.cluster.local/172.30.101.86:9093) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
2021-07-13 11:44:42,818 ERROR inclient-1 o.a.k.c.NetworkClient      [AdminClient clientId=adminclient-1] Connection to node -1 (my-cluster-kafka-bootstrap.blz.svc.cluster.local/172.30.101.86:9093) failed authentication due to: SSL handshake failed
2021-07-13 11:44:42,818 WARN  inclient-1 c.a.i.AdminMetadataManager [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
Caused by: javax.net.ssl.SSLProtocolException: Unexpected handshake message: server_hello
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(Unknown Source)
	at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:430)
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:514)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:291)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1333)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1264)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by blezoray** [comment]
Hi, do you have additional tuning to limit these error messages ?

**Comment by tchiotludo** [comment]
Not really sure to understand here ? 
If you open to configuration `my-cluster-sasl-tls` and `my-cluster-tls` on the same host and the same port with 2 different configuration, it's not possible as I know, kafka don't allow 2 different auth on the same port ... 
Maybe you can explain more ?

**Comment by blezoray** [comment]
You're right.
I put these 2 kafka cluster configurations in a Openshift template, in which it is not possible to disable some parts of the template, compared to helm chart. 
So I would like to limit errors logs in case users open the wrong cluster configuration.

**Comment by tchiotludo** [comment]
Not really sure to understand, but you should be able to remove the log with this : 
```yaml
logger:
  levels:
    # Disable SSL handshake failed error logs
    org.apache.kafka.common.errors.SslAuthenticationException: ERROR
    org.apache.kafka.clients.admin.internals.AdminMetadataManager: ERROR
akhq: 
...
````

**Comment by blezoray** [comment]
It's better. Thanks.
