### ISSUE TITLE
Can't connect to Kafka via SASL_SSL mechanism PLAIN

### ISSUE THREAD

**Issue by fra-luc** [tchiotludo/akhq#766]
Hello!
I'm quite new to Kafka and I am looking for some help, I am trying to connect to a Kafka broker with this ahkq config:

```
akhq:
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "broker:9092"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.username: user
        sasl.password: password
```

But I get the following error from ahkq:
```
2021-07-21 10:47:40,911 ERROR Group-1-10 o.a.c.ErrorController      Failed to create new KafkaAdminClient
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:499)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:63)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
	at org.akhq.modules.KafkaModule.getAdminClient(KafkaModule.java:100)
	at org.akhq.modules.AbstractKafkaWrapper.listTopics(AbstractKafkaWrapper.java:52)
	at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$$exec2.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:73)
	at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$Intercepted.listTopics(Unknown Source)
	at org.akhq.repositories.TopicRepository.all(TopicRepository.java:65)
	at org.akhq.repositories.TopicRepository.list(TopicRepository.java:57)
	at org.akhq.controllers.TopicController.list(TopicController.java:80)
	at org.akhq.controllers.$TopicControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:474)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$10(RoutingInBoundHandler.java:1363)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:148)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set
	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:133)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:98)
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:84)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:134)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:73)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:474)
	... 29 common frames omitted
```

I suppose the JAAS configuration is missing, but how do I set it up properly?
Thanks!

**Comment by twobeeb** [comment]
Hi,

The config you're looking for is available in the example provided : https://github.com/tchiotludo/akhq/blob/dev/application.example.yml#L118-L123

**Comment by tchiotludo** [comment]
Thanks @twobeeb for help ;)

**Comment by fra-luc** [comment]
Thanks!
