### ISSUE TITLE
Unable to view schema/topics if one Schema Registry subject does not have subject-level compatibility set

### ISSUE THREAD

**Issue by farukciber** [tchiotludo/akhq#785]
**Exception**: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'mysubject-value' does not have subject-level compatibility configured; error code: 40408

It would be good to use the global schema compatibility level instead of throwing the exception.

**Comment by tchiotludo** [comment]
Can you send me the full stacktrace please ?

**Comment by farukciber** [comment]
Internal Server Error: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'mysubject-value' does not have subject-level compatibility configured; error code: 40408


java.lang.RuntimeException: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'sample' does not have subject-level compatibility configured; error code: 40408
	at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLastestVersion$1(SchemaRegistryRepository.java:51)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$SubList$2.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.akhq.repositories.SchemaRegistryRepository.toSchemasLastestVersion(SchemaRegistryRepository.java:54)
	at org.akhq.repositories.SchemaRegistryRepository.lambda$list$0(SchemaRegistryRepository.java:38)
	at org.akhq.utils.PagedList.of(PagedList.java:70)
	at org.akhq.repositories.SchemaRegistryRepository.list(SchemaRegistryRepository.java:38)
	at org.akhq.controllers.SchemaController.list(SchemaController.java:51)
	at org.akhq.controllers.$SchemaControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:469)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:312)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:118)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$9(RoutingInBoundHandler.java:1352)
	at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14868)
	at org.akhq.middlewares.HttpServerAccessLogFilter$HttpServerPublisher.subscribe(HttpServerAccessLogFilter.java:130)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher.subscribe(WebMetricsPublisher.java:153)
	at io.micronaut.http.server.context.ServerRequestContextFilter.lambda$doFilter$0(ServerRequestContextFilter.java:62)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:148)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'mysubject-value' does not have subject-level compatibility configured; error code: 40408
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:292)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:351)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getConfig(RestService.java:591)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getConfig(RestService.java:580)
	at org.akhq.repositories.SchemaRegistryRepository.getConfig(SchemaRegistryRepository.java:203)
	at org.akhq.repositories.SchemaRegistryRepository.getLatestVersion(SchemaRegistryRepository.java:108)
	at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLastestVersion$1(SchemaRegistryRepository.java:49)
	... 35 more

**Comment by tchiotludo** [comment]
Thanks, seems that you are not using the last version so I try a fix.
You can try with `dev` version in 10 minutes

**Comment by farukciber** [comment]
Are you sure this is the fix? The error code is 40408 so the exception will still be thrown.

Would it be good to add a check for 40408 error code in the if statement?

`if (exception.getErrorCode() != ERROR_NOT_FOUND && exception.getErrorCode() != SUBJECT_LEVEL_COMPATIBILITY_NOT_FOUND) {
                throw exception;
            }`

**Comment by tchiotludo** [comment]
you are true, this was already fix here I think https://github.com/tchiotludo/akhq/pull/765.
I revert my change ;)

**Comment by farukciber** [comment]
Sorry I didn't see that issue, somehow I missed it. 

Thanks

**Comment by tchiotludo** [comment]
np @farukciber, really to follow issue on a github project ;)

**Comment by tchiotludo** [comment]
@n-i-c-o-l-a-s try the last version and open new bug if it's not working please

**Comment by n-i-c-o-l-a-s** [comment]
Perfect. The [0.19.0](https://github.com/tchiotludo/akhq/releases/tag/0.19.0) fixed the problem. Thanks a lot.
