### ISSUE TITLE
IndexOutOfBoundsException thrown in topics view when changing to cluster with fewer pages

### ISSUE THREAD

**Issue by ahalaj** [tchiotludo/akhq#835]
Using version 0.18.0

When I am on Topics view in the UI and I go to the last page and then I change my cluster to a different one, which has fewer pages, I get this exception:

```
java.lang.IndexOutOfBoundsException: toIndex = 150
	at java.base/java.util.AbstractList.subListRangeCheck(Unknown Source)
	at java.base/java.util.ArrayList.subList(Unknown Source)
	at org.akhq.utils.PagedList.of(PagedList.java:67)
	at org.akhq.repositories.TopicRepository.list(TopicRepository.java:62)
	at org.akhq.controllers.TopicController.list(TopicController.java:81)
	at org.akhq.controllers.$TopicControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:151)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:482)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:121)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.emitRouteResponse(RoutingInBoundHandler.java:1533)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.access$2100(RoutingInBoundHandler.java:151)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6$1.request(RoutingInBoundHandler.java:1500)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onSubscribe(FlowableFlatMap.java:656)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.doSubscribe(RoutingInBoundHandler.java:1488)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.lambda$subscribe$0(RoutingInBoundHandler.java:1482)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:157)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by EdwinFajardoBarrera** [comment]
I would like to work on this, can you assign me?

**Comment by tchiotludo** [comment]
@EdwinFajardoBarrera done :+1:

**Comment by tchiotludo** [comment]
done in #962
