### ISSUE TITLE
java.io.IOException: Is a directory

### ISSUE THREAD

**Issue by omnipresent07** [tchiotludo/akhq#857]
I am trying to run kafka hq using the docker image like blow

```
docker run -d \
    -p 9080:8080 \
    -v application.yml:/app/application.yml \
    tchiotludo/akhq
```

Here is my `application.yml`

```
micronaut:
  connections:
    my-cluster-plain-text: 
      properties:   
        bootstrap.servers: "localhost:9092"
      schema-registry:
        url: "http://localhost:8081" 
        type: "confluent"
```

Below is the error I get by doing `docker log` -- the container never comes up.

```
2021-10-18 02:02:28,644 ERROR main       i.m.runtime.Micronaut      Error starting Micronaut server: java.io.IOException: Is a directory
org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Is a directory
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176)
        at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171)
        at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
        at org.yaml.snakeyaml.composer.Composer.checkNode(Composer.java:82)

```

**Comment by tchiotludo** [comment]
I think you should use this command in order to mount local file : 
```yaml 
docker run -d \
    -p 9080:8080 \
    -v ./application.yml:/app/application.yml \
    tchiotludo/akhq
````

see https://stackoverflow.com/a/48442262/1590168
