### ISSUE TITLE
Add defaultToGlobal=true querystring to schema registry query

### ISSUE THREAD

**Issue by Thiago-Dantas** [tchiotludo/akhq#906]
Currently we cannot use the Schema Registry portion of AKHQ because our topics rely on the global compatibility level

Without the [defaultToGlobal querystring](https://docs.confluent.io/platform/current/schema-registry/develop/using.html#show-compatibility-requirements-in-effect-for-a-subject) we get the error `Subject 'schema-name' does not have subject-level compatibility configured; error code: 40408` [defined here](https://github.com/confluentinc/schema-registry/blob/cd39f6739301b252eabaf805ae0a15b3301ff579/core/src/main/java/io/confluent/kafka/schemaregistry/rest/resources/ConfigResource.java#L124)

Please consider adding this option

**Comment by tchiotludo** [comment]
Which version of AKHQ ?

**Comment by Thiago-Dantas** [comment]
I'm using the current docker image at tchiotludo/akhq:latest

**Comment by twobeeb** [comment]
I never observed this behavior yet we rely heavily on global compatibility level.
Do you see this issue in 0.18 ? Could you share detailled errors logs or screenshots where you have this issue ?

**Comment by Thiago-Dantas** [comment]
![image](https://user-images.githubusercontent.com/6326626/142430360-2ca2a661-59f7-443c-984c-6a76cc735da4.png)

```
2021-11-18 14:06:01,625 [1;31mERROR[0;39m [35mpGroup-1-4[0;39m [36mo.a.c.ErrorController     [0;39m io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'meiosdepagamento__db_eldorado-key' does not have subject-level compatibility configured; error code: 40408
--
java.lang.RuntimeException: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'meiosdepagamento__db_eldorado-key' does not have subject-level compatibility configured; error code: 40408
at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLatestVersion$1(SchemaRegistryRepository.java:55)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.base/java.util.ArrayList$SubList$2.forEachRemaining(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
at org.akhq.repositories.SchemaRegistryRepository.toSchemasLatestVersion(SchemaRegistryRepository.java:58)
at org.akhq.repositories.SchemaRegistryRepository.lambda$list$0(SchemaRegistryRepository.java:42)
at org.akhq.utils.PagedList.of(PagedList.java:70)
at org.akhq.repositories.SchemaRegistryRepository.list(SchemaRegistryRepository.java:42)
at org.akhq.controllers.SchemaController.list(SchemaController.java:51)
at org.akhq.controllers.$SchemaControllerDefinition$exec1.invokeInternal(Unknown Source)
at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:151)
at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:482)
at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:121)
at io.micronaut.http.server.netty.RoutingInBoundHandler.emitRouteResponse(RoutingInBoundHandler.java:1533)
at io.micronaut.http.server.netty.RoutingInBoundHandler.access$2100(RoutingInBoundHandler.java:151)
at io.micronaut.http.server.netty.RoutingInBoundHandler$6$1.request(RoutingInBoundHandler.java:1500)
at io.micronaut.http.server.netty.async.ContextCompletionAwareSubscriber.doOnSubscribe(ContextCompletionAwareSubscriber.java:49)
at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onSubscribe(CompletionAwareSubscriber.java:38)
at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onSubscribe(WebMetricsPublisher.java:162)
at org.akhq.middlewares.HttpServerAccessLogFilter$HttpServerPublisher$1.onSubscribe(HttpServerAccessLogFilter.java:133)
at io.micronaut.http.server.netty.RoutingInBoundHandler$6.doSubscribe(RoutingInBoundHandler.java:1488)
at io.micronaut.http.server.netty.RoutingInBoundHandler$6.lambda$subscribe$0(RoutingInBoundHandler.java:1482)
at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:157)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Subject 'meiosdepagamento__db_eldorado-key' does not have subject-level compatibility configured; error code: 40408
at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:295)
at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:355)
at io.confluent.kafka.schemaregistry.client.rest.RestService.getConfig(RestService.java:604)
at io.confluent.kafka.schemaregistry.client.rest.RestService.getConfig(RestService.java:593)
at org.akhq.repositories.SchemaRegistryRepository.getConfig(SchemaRegistryRepository.java:207)
at org.akhq.repositories.SchemaRegistryRepository.getLatestVersion(SchemaRegistryRepository.java:112)
at org.akhq.repositories.SchemaRegistryRepository.lambda$toSchemasLatestVersion$1(SchemaRegistryRepository.java:53)
```

We are using the latest AKHQ docker image and also the latest schema registry image at `confluentinc/cp-schema-registry:latest`

**Comment by twobeeb** [comment]
Interesting, should be fixed : #763

Maybe your "latest" is older than the fix ?

**Comment by Thiago-Dantas** [comment]
Depends if its been pushed to docker hub, I just built my image.
My Dockerfile is simply switching to USER root to use port 80

**Comment by tchiotludo** [comment]
Just see the issue :) 
I forgot to push to latest. 
Just done right now : https://hub.docker.com/layers/tchiotludo/akhq/latest/images/sha256-184773dd936de7fc1b6b26be53d1ffd53703ee77feae5fc09b3efccf2da4ccd2?context=explore

**Comment by dinegri** [comment]
After changing from  Schema Registry version 5.3.0 to version to 6.1.2 we got those errors as well

Thanks for the fix :)
