### ISSUE TITLE
Serialise Java 8 java.time.ZonedDateTime with com.fasterxml.jackson.datatype:jackson-datatype-jsr310

### ISSUE THREAD

**Issue by anilsahin** [tchiotludo/akhq#918]
As part of upgrading akhq from version 0.14.1 to version 0.19.0, serialisation to https://github.com/tchiotludo/akhq/blob/0.19.0/src/main/java/org/akhq/models/Record.java#L40 which appears to be of Java 8 type java.time.ZonedDateTime fails with the following trace that is also displayed on the UI.

```
Internal Server Error: Error encoding object [{"omitted"}] to JSON: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.concurrent.ConcurrentHashMap["omitted-topic-name"]->org.akhq.models.Record["timestamp"])

io.micronaut.http.codec.CodecException: Error encoding object [{"omitted"}] to JSON: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.concurrent.ConcurrentHashMap["omitted-topic-name"]->org.akhq.models.Record["timestamp"])
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:233)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:257)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeBodyAsByteBuf(RoutingInBoundHandler.java:2087)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeBodyWithCodec(RoutingInBoundHandler.java:2031)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeResponseBody(RoutingInBoundHandler.java:1817)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.encodeHttpResponse(RoutingInBoundHandler.java:1729)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.access$100(RoutingInBoundHandler.java:151)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$5.onComplete(RoutingInBoundHandler.java:1416)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$5.onComplete(RoutingInBoundHandler.java:1119)
	at io.micronaut.http.server.netty.async.ContextCompletionAwareSubscriber.doOnComplete(ContextCompletionAwareSubscriber.java:73)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onComplete(CompletionAwareSubscriber.java:71)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onComplete(WebMetricsPublisher.java:191)
	at org.akhq.middlewares.HttpServerAccessLogFilter$HttpServerPublisher$1.onComplete(HttpServerAccessLogFilter.java:149)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.emitRouteResponse(RoutingInBoundHandler.java:1693)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.access$2100(RoutingInBoundHandler.java:151)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6$1.request(RoutingInBoundHandler.java:1500)
	at io.micronaut.http.server.netty.async.ContextCompletionAwareSubscriber.doOnSubscribe(ContextCompletionAwareSubscriber.java:49)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onSubscribe(CompletionAwareSubscriber.java:38)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onSubscribe(WebMetricsPublisher.java:162)
	at org.akhq.middlewares.HttpServerAccessLogFilter$HttpServerPublisher$1.onSubscribe(HttpServerAccessLogFilter.java:132)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.doSubscribe(RoutingInBoundHandler.java:1488)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.lambda$subscribe$0(RoutingInBoundHandler.java:1482)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:157)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.ZonedDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: java.util.concurrent.ConcurrentHashMap["omitted-topic-name"]->org.akhq.models.Record["timestamp"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1276)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:770)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:869)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3701)
	at io.micronaut.jackson.codec.JacksonMediaTypeCodec.encode(JacksonMediaTypeCodec.java:231)
	... 26 more
```

Simply passing the jar for jackson-datatype-jsr310 to our docker image and setting the `CLASSPATH` env variable accordingly has also not solved the issue.

Would this dependency need to be included with https://github.com/tchiotludo/akhq/blob/0.19.0/build.gradle#L101 and used in the app or does anyone know a way to mitigate this that we miss? Thank you!

**Comment by tchiotludo** [comment]
Humm strange :thinking: 

Look [here](https://github.com/tchiotludo/akhq/blob/bc0cfb75d44b7cf792aa2840f701fac276a277f9/src/main/java/org/akhq/modules/AvroSerializer.java#L35): The module is already included here. 

also : 
```
./gradlew dependencies | grep jsr310
|    |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.2 (c)
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.11.1 -> 2.12.2
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.3 (c)
```
The lib is included as transitive deps... 

Are you using the official docker version ?

**Comment by anilsahin** [comment]
Alright yes does look like it is indeed already included.

For the docker image yes I believe so we are using `tchiotludo/akhq:0.19.0` as base image.

**Comment by tchiotludo** [comment]
Just notice that the error is coming from webserver, can you share your configuration files please ?

**Comment by anilsahin** [comment]
here is the configuration we have for jackson:
```
jackson:
  module-scan: false
  jackson.serialization-inclusion: NON_DEFAULT
  serialization:
    writeDatesAsTimestamps: false
```

**Comment by tchiotludo** [comment]
Ok remove all the jackson configuration and it will work

**Comment by anilsahin** [comment]
Thanks you! Yes I can confirm that it works after removing the jackson configuration
