### ISSUE TITLE
Error on node lost from cluster

### ISSUE THREAD

**Issue by ddellarocca** [tchiotludo/akhq#943]
Hi,
I'm facing the following issue, in a cluster with 3 kafka nodes on 3 different server each one with its own zookeeper, if a node is detached from the cluster i get the following error while listing topics:

```
java.lang.RuntimeException: Error for Describe Topics Offsets {}
	at org.akhq.utils.Logger.call(Logger.java:31)
	at org.akhq.modules.AbstractKafkaWrapper.describeTopicsOffsets(AbstractKafkaWrapper.java:122)
	at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$$exec6.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:151)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:87)
	at org.akhq.modules.$KafkaWrapperRequestScopeDefinition$Intercepted.describeTopicsOffsets(Unknown Source)
	at org.akhq.repositories.TopicRepository.findByName(TopicRepository.java:112)
	at org.akhq.repositories.TopicRepository.lambda$list$0(TopicRepository.java:62)
	at org.akhq.utils.PagedList.of(PagedList.java:70)
	at org.akhq.repositories.TopicRepository.list(TopicRepository.java:62)
	at org.akhq.controllers.TopicController.list(TopicController.java:81)
	at org.akhq.controllers.$TopicControllerDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:151)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:482)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:121)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.emitRouteResponse(RoutingInBoundHandler.java:1533)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.access$2100(RoutingInBoundHandler.java:151)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6$1.request(RoutingInBoundHandler.java:1500)
	at io.micronaut.http.server.netty.async.ContextCompletionAwareSubscriber.doOnSubscribe(ContextCompletionAwareSubscriber.java:49)
	at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onSubscribe(CompletionAwareSubscriber.java:38)
	at io.micronaut.configuration.metrics.binder.web.WebMetricsPublisher$1.onSubscribe(WebMetricsPublisher.java:162)
	at org.akhq.middlewares.HttpServerAccessLogFilter$HttpServerPublisher$1.onSubscribe(HttpServerAccessLogFilter.java:133)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.doSubscribe(RoutingInBoundHandler.java:1488)
	at io.micronaut.http.server.netty.RoutingInBoundHandler$6.lambda$subscribe$0(RoutingInBoundHandler.java:1482)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:157)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 15001ms
```

If the node is then reattached to the cluster the error is solved, in my case the topics are replicated in at least two nodes so if i detach a node from the cluster i expect to keep using akhq as usual and not to see any errors.

**Comment by tchiotludo** [comment]
Really old one issue and complicated, see : 
- https://github.com/tchiotludo/akhq/issues/137
