### ISSUE TITLE
No consumer groups, you can click on next page 

### ISSUE THREAD

**Issue by tchiotludo** [tchiotludo/akhq#976]
and will lead to this error : 
```
2022-01-05 10:33:19,246 INFO r-thread-2 org.akhq.log.access [Date: 2022-01-05T10:33:19.235602Z] [Duration: 10 ms] [Url: GET /api/localhost/group] [Status: 200] [Ip: /192.168.110.21] [User: -]
2022-01-05 10:33:23,002 ERROR r-thread-3 o.a.c.ErrorController fromIndex = -25
java.lang.IndexOutOfBoundsException: fromIndex = -25
at java.base/java.util.AbstractList.subListRangeCheck(AbstractList.java:505)
at java.base/java.util.ArrayList.subList(ArrayList.java:1138)
at org.akhq.utils.PagedList.of(PagedList.java:67)
at org.akhq.repositories.ConsumerGroupRepository.list(ConsumerGroupRepository.java:42)
```

**Comment by EdwinFajardoBarrera** [comment]
I would like to work on this!

**Comment by tchiotludo** [comment]
It's for you 😉
